### ISSUE TITLE
[suggestions] Line heights, description to comment

### ISSUE THREAD

**Issue by hongkiulam** [tokens-studio/sd-transforms#11]
Hey!
Great to see this package, I had also implemented the majority of these transforms in my own workflow :)

Two which are missing here which I think _may_ be worth adding

# Line heights
In Figma tokens, we can apply line heights by using percentages. This applies per element in Figma, and correctly multiplies the font size. However, the behaviour of percentage line heights in CSS is different to how it works in Figma. Full reasoning can be found here: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height, but TLDR is that unit-less line-heights are recommended e.g. `150% -> 1.5`

example transform
```js
StyleDictionary.registerTransform({
    name: "lineHeightPercentageToDecimal",
    type: "value",
    matcher: (token) =>
      token.type === "lineHeights" && token.value.endsWith("%"),
    transformer: (token) => {
      const rawNumber = Number(token.value.replace("%", ""));
      const percentageAsDecValue = rawNumber / 100;
      return percentageAsDecValue;
    },
  });
```

# Description to comment

Perhaps an opt-in transform, but i found it useful to use the Figma tokens descriptions as code comments

```js
  StyleDictionary.registerTransform({
    name: "descriptionToComment",
    type: "attribute",
    matcher: (token) => token.description,
    transformer: (token) => (token.comment = token.description),
  });
```
<img width="402" alt="image" src="https://user-images.githubusercontent.com/58468238/216839029-4e2b685d-ff60-4256-bcaf-930cad1c70b3.png">

**Comment by jorenbroekema** [comment]
@six7 thoughts?

First one seems like a must to me.

Second one, I am guessing some built-in formats use comment property to add comments already by default? In that case I guess this one is helpful as well, otherwise I don't really see a reason to add it since your custom format can easily use the description property to get this in the platform output.

@hongkiulam would you be open to create a PR for these if Jan agrees?

**Comment by hongkiulam** [comment]
Yeah happy to do a PR, I'm fine with leaving out the second one, that one is more subjective for sure

**Comment by six7** [comment]
I think both of these make sense! The comment property afaik is picked up by some sd formats that treat it like a comment depending on the output. Thanks for creating this issue even prior to us officially launching this 🙏
