### ISSUE TITLE
[Bug]: TypeError: Color is not a constructor

### ISSUE THREAD

**Issue by justingorham-tesouro** [tokens-studio/sd-transforms#111]
### What happened?

I'm getting the following error when using the token-studios transform group.

```
/root/node_modules/@tokens-studio/sd-transforms/dist/color-modifiers/modifyColor.cjs:13
    const color = new Color(baseColor);
                  ^

TypeError: Color is not a constructor
    at Object.modifyColor (/root/node_modules/@tokens-studio/sd-transforms/dist/color-modifiers/modifyColor.cjs:13:19)
    at Object.transformColorModifiers (/root/node_modules/@tokens-studio/sd-transforms/dist/color-modifiers/transformColorModifiers.cjs:10:24)
    at Object.transformer (/root/node_modules/@tokens-studio/sd-transforms/dist/registerTransforms.cjs:144:55)
    at transformProperty (/root/node_modules/style-dictionary/lib/transform/property.js:41:36)
    at transformObject (/root/node_modules/style-dictionary/lib/transform/object.js:83:30)
    at transformObject (/root/node_modules/style-dictionary/lib/transform/object.js:90:30)
    at Object.exportPlatform (/root/node_modules/style-dictionary/lib/exportPlatform.js:97:25)
    at Object.buildPlatform (/root/node_modules/style-dictionary/lib/buildPlatform.js:56:21)
    at /root/node_modules/style-dictionary/lib/buildAllPlatforms.js:31:10
    at Array.forEach (<anonymous>)

```

### Reproduction

```javascript
const { registerTransforms } = require('@tokens-studio/sd-transforms');
const StyleDictionary = require('style-dictionary').extend({
  source: ['/root/tokens/**/*.json'],
  platforms: {
    ts: {
      transformGroup: 'tokens-studio',
      buildPath: '/root/output',
      files: [
        {
          destination: 'variables.js',
          format: 'javascript/es6',
        },
      ],
    },
  },
});

registerTransforms(StyleDictionary);

StyleDictionary.buildAllPlatforms();

```

### Version

0.8.3

**Comment by justingorham-tesouro** [comment]
The following gets around the issue (though it is not a sustainable workaround).

![image](https://user-images.githubusercontent.com/113395333/234414844-464c72bf-0255-4466-ae1b-bbe6d0b6afa0.png)

**Comment by jorenbroekema** [comment]
Yeah this issue is a common CJS / ESM interoperability problem, default exports work differently in these formats. I'll see if I can find a fix in the Rollup CommonJS plugin for this and distribute a new version of sd-transforms where this is fixed

**Comment by jorenbroekema** [comment]
I checked locally in a CommonJS script and I could reproduce your error.
For me it's fixed now, now that I handle default export ESM/CJS interoperability similar to how Babel and TypeScript (`esModuleInterop`) would handle them (using `__esModule` property hack in modules).

In case you're curious, `colorjs.io` and similar CJS modules with default exports, will do something like `Object.defineProperty(exports, '__esModule', { value: true });`, to signify that for a default import, we should refer to the default export "default" property. I double-checked that our external dependencies that contain default exports all have this meta info and fortunately, they do :).

Then in this library in the CJS files a helper will then use this information, Rollup inserts a helper when necessary if interop is enabled:
```js
var Color = require('colorjs.io');

function _interopDefault (e) { return e && e.__esModule ? e : { default: e }; }

var Color__default = /*#__PURE__*/_interopDefault(Color);
```
