### ISSUE TITLE
Provide examples

### ISSUE THREAD

**Issue by six7** [tokens-studio/sd-transforms#120]
One piece missing still for users wanting to try to use `sd-transforms` is they have to setup everything needed in order to run it. This is a tedious step for someone who's not proficient with `style-dictionary` or `sd-transforms`.

What we should do is provide a couple of examples that will help someone get started quicker.

## Examples to build
- Multi-file sync example with very simple setup: Only `Color: Light/Dark` sets are setup, and only tokens of type color including color modifiers
- Multi-file sync example with a more complex setup involving `color`, `typography`, `composition`, `boxShadow` and `border` tokens as well as `math` tokens
- Single-file sync example where root keys are the sets

We should then link to these examples from the readme, and provide a root level folder of `examples` so someone exploring the repository can easily find those.

This should help to point users towards a setup that they can build on themselves. It should also help us to setup a Codesandbox that we can use to send users for reproduction purposes.

**Comment by jorenbroekema** [comment]
- simple: https://github.com/tokens-studio/sd-transforms?tab=readme-ov-file#usage
- themes: https://github.com/tokens-studio/sd-transforms?tab=readme-ov-file#themes-complete-example
- multi-themes: https://github.com/tokens-studio/sd-transforms?tab=readme-ov-file#multi-dimensional-theming
