### ISSUE TITLE
[Feature]: Exported Swift code doesn't compile

### ISSUE THREAD

**Issue by krris** [tokens-studio/sd-transforms#132]
### What happened?

Hi all 👋

I am investigating if we can use Token Studio at the current company in the iOS project. I was playing with code generation for Swift and unfortunately I wasn't able to get the output in Swift that compiles.

### Reproduction

1. Open https://configurator.tokens.studio/
2. Don't upload tokens -  use default studio.token.json that are provided as an example
3. Add a new platform with:
  * transforms: `ios-swift`
  * formats: `ios-swift/class.swift`
4. Click "Run Style Dictionary"

Here's [the link to reproduce the issue](https://configurator.tokens.studio/#project=5VwLj9s2Ev4rwrZFHljbekt2rodDm0tSIEGLbNC0uC2uelC2GlkyJDnZvcX+9yM5pJ4UbW0ktHdJgHZX82mGnOGQ4kdO7i78Y5yEq6AoVv/+6OWx5yeoWOJfLzYXq6dPr1PlqfI8U9KsVFAYl0oY5ygok1sqeIlSlHslCpUsVd5k6aWi68ob71bRVd1Q1PXGWm/wk5dv3hH46jq9Tjd5hlXd4d+VxaIIn8d7lBZxll4FXoI2iv6sJ/ml2Cjm4aYvuNpvFFckeBNuFM0WSV5vN4qhiyS/JBvFbpq5OnhBnG671tnjrm32uGeZPe/Z5doHrL45JmX8s5ccETUDGGX1VPk1OyqBlyo77yNS9gR1SJDykSALJU4VTynw6/hRAYqUMvuA0qXyFnmhss9yRCJV7lCBFe/K8lBsVqswC4olxRXLojyGcbbyPnpxQobCAp6vmDr261fU8oKaXbRFNMzQl++yPET5Wy+MjwXxV7OfTRlxjjsgIw5qObQpbHoJK6dKRjkpp2qm8pFPm7YApdxTYGmx4M1YsGbUbvo+S7K8+C7xgg8b5SuV/nnWFr7fxSVuzFcR/dMRvsy9W01VidiJvCgQiHUqRmGkR45AbIBYR26kCsQmFQd+aCGR2KJiT/VQIBLbVOxorrq2BWKHik3PsmxXIHapWA8NxxSJ11SseXi+6fb7LQqpV3ZF8lhVXGfpfqO46tL55kkfqHeBjrO0RECjBzSXhgho9oDaUhMBwXuRZeO/fandVWMPqHG6QGugYW4XaA50dd0Dipz3Y+6lW8SGX4SHnyoEwACMEPIDVwiAIRj5oeGGQgAMwsj2QssSAiw2xt21YQsBMBDD0PZ1cSNhKAaqZeuaEACDcR2Y+gAAhqPjG6aGOoBfUZJknypHRT1HAYA7Kgr8SAhgjsKOdtdCAHcUUi1xG5ijgmBt+kIAc5S9xjOCEACO8h1nrYkbyRzlWJ5mCwHMUaapa/05A6GU+UnFfjJFcnBTYEd2aInk4KW1h2xf+D44yXZDY62J5OAj0/V9xxXJwUWGi/u3FsnBQ3rkWpYnkrNpzbEdU/g++EfXLdPopsM75CXgHmSTjBOIwTu+HllIJAbnuBqyw7VADL4xo1ALLIHYYl33dS8QiJlntLWzFr3NHBM4nuMLxMwvroVsTSBmbjFMZOnPuuvnkU1DyI/c3iJJxMwtCBmRKxCzMaMGYW/METEbMoZvoFAgZiNGX6+RJhBzt7h6gARi5hbfDnxVIGZuCSzdFfWbucUzjd4a8kMaxtuscozZcwwAWD4ZoRchIQCc4xl+f8QBANzjROsgErcBHGTbDkJiDeAiy7Od0BUC2KdCYGm+uBfgJhPPvmtVCABHGYFh293R99Mxx19nGp9drZ6jAMC+pNahG4VCgMEmTz/oOQoAJps812ZvmAEAHLWOHA+JNYCjXNXyepMfAMBReOqzA00IAEdZlhGsxSbAUaZpGE4PEKcfqmXM6n1PEjFfxEIH6QIxX+vxaEcCMV/AXLyOCsR8nbdNzxaI2eJl4RwPBGK2dLmG7qoCMV+4dNsOBWK2bKm6adUz549k/1Pevs4+bRR1qXWfky2hurS6j1/F2x0R1HpeZGn5wtvHSYyKV3grgjcOG+WHtES5EPJdFt5ulLeZn5VZBXgdp+gVwqrLWoXWaFNDDu9ry3oQvkYlNsZ2oM9R5OEtC26iWP5DGuTIKxDZ8C4ttB/SUqEW6lJt4n7ycm+be4cdg77SyBZ5WKxjcsBueeJ9q6Nv0faYeDneCTa2T33Yd1mCG+OIMcQnp/QQjFjJVfwfHDncDdNdunpzR1tLcS+M9VK1DaHUwFJtqVtCoYkdIJZYWKIKJXZn91xJWPSFMrJX14ylUEboEE1dNrfy/7zx9njKuNp5IUmBOC1Qqah0Q67hVuEf863vPVYv6d+lSbYQ99fpxSWjnv4oVjXx9MdcvBO6OWR5qQRZWhBlTdZJ+Va5vtCvL54NoX4pKAT3SAK62lOQKwW9CSmI+F2Cer2lKEIYyVqVUJQtbFbB2avhlhecyRpud8FZLUmrC85wSdrMW3NGi2tOhzdLYXhltfrr01+dTvktCmw4Fn6LDhsOiN+ixiRR8YU0GW+A4o736J/HlXW6FtR8Ge0Po8z6Pghq7gyAQJ8NARmPxqCUSpNBdQ4FWk0GNSoopdhkUJNDgW6TQS0OBepNBrU5FGg4GdThUKDkZFCXQ4Gek0HXHApU3RAUODuK7NN2kpd0wUtA4UleMkQvUdZM8pIpeolycpKXqkgBzSdB2gL19in1juAl61RHXMFL5imXrUUvSYNT8YNVBnrDCVBxhQxM6UI5uEotoA7l4Cq5gEaUg606vwmlKAdXCQb0ohxcpRhQjXJwlWRAO8rBVZoBBTkErrjIxrSoysGNoBBqUg6ug0JpSjm4ERRCWcrBdVAofSkH10GhVKYcXAUFaE05uA4KpTjl4DoolO4cniaB92TOoNSnFFuFBGhQKbaKCFCiUmwVEKBHpdgqHkCVSrFVOIA2lWKraACFKsXWyxClU6XYKhZArQ5hGcfKhhqlWWXQKhJAucqgVSCAfpVBqzgAFSuDWrVrCS0rg9ZRoBStDFoHgdK1MmgdA0rdyqB1CCiNOwRlfC4LAaV0ZdA6BJTelUHrXKBUrwxapwKlfWXQOhMoBSyDNkJA6GAZtA4BpYZl0DoElCaWQesQUMp4CFpxx1UQzOEgVDwym5MolSwHV4EAWlkOrkIBFLMcXAUD6GY5uAoHUM9ycP15TGloObgKCVDScnAVFKCnh8AVT12tsNZwUCrOmkWQ0tZysFEvmoTCloPNetEkdLYcXAUFqG05uAoK0NxycBUUoLzl4CooQH/LwVVQgAofBAMnXn1OWcP7QcaP848pQpHLoI3vW0KXy6CNDylCncugjW9bQqPLoPVHFKXUZdD6E4rS6zJo4wOKUO0yaP35RGn3PjSr+HeKwxT8IIYRWZiOH4QQXp6BBLaiPkdPwZSml8MJ40qxQNn3wUmPuwd+R9SfpM3jM6AgARMBpw/dO4Gt+H2mG1P3J7U332B0f/+dQ4/3Z8ThGVAdqFpb7GnheQBQXiJ6KBKeDVC8cwLfOCc4Sz8/M5ArZ+cHoJEdIciQ4A1+nCBDGoCEowUZ0AQHn0BZgFLlKFtCT0bNc4hzcIw8hWMJCY4R3nBE0ceh5lkFRZ4+rsBa8FkFfj+Kt/h8IkvxCcUdOfy4viiyY04m5Y3yL/KAPHr6dPWUk58EfH1BJL9dwguHxCujLN8X5J07/k7841Xjd/KEnoz85JU78pz9usKw1fXFZY065CiKbwDSEpSYDSiInZd5djwAIM6KRfEpjsoWMorxqUujA+TPXf0jgYSoKOPUK2PSGaLpHaN2O8qYQmzVKzsmV0HiFdUb9Qv3/Mff4Af6O/7PPXZ4jrZxQWaX5y+OaUCss9OheE8DelXeJuh5TCVefqtEebZXHhXk6SKsHj/CI4C9cKdwle+4ewrlnr33DwjZgvHVRbiofFgQHdcp5spbT/GZUxrSKWqPsE48BHO8htB2UkLdR4oXhnjTQN68QkghtHhNkm/jcnf0l0G2X0lMX6f9Nj/u9PwJbx4b3EDeK5WSS+XTLg52yh9HnAA5Ko85biGm7IHKVzxM82M7HaXLnt3HdFiUtwdEQkttsOCn2APk2f72e2wi21evMDkeD8EO4RPVx9TiE+Xbvyt391RUNbIrhvEArYWG0tOKvy0W9Tuk6SlC1McwbJ4wT8AgVHYoOaC8gBB3R8Z1ClPCnUJygKwAKL9kb+KTxZ/5kSQeIt92B9sSYK9Af9f/QVEwPcNufUHl4FPw3yPuPhA9ov7hzcHeiVgWPL6r+3BJ237Jx939E+443rXsWB6O5VsUoRylAesMQz9r+fj3r+9qPzymP98/ua9u62NpzzOP2TPcdtzlR5dKs2Fdy1gZDtDvz6pQPaNHwDDomxNmPbtWJ52tybIgR7ad6ZKNRjII9fZEiIcrPN/TyZRNM5dc2U0xrIkuIEJdjYZ1FRb7YYV31XvLm+IeH2M3HtBe3Y+3tw/PslfsJ7KXbM+ytw8nsneTnGUv2X6ePToq2RrNDnRbg042TtphHTBZKX3ggMEBHKv5zKGBQzVW85mDAAdlrOYzw32TjPdGfWR/dsaMs9iQ4k+mII8P9SfTX//egigTmpcI2nOwZNCaA35qKxszpNwHaZQNJXJk8wCV542hpg4YRq0nw1nRNj7JcPoTL22IBhSwOq2h5JN7HMPerC53CD1G9fXj9Ilc+ZDo5PdAxujEPMRtR6VG2rVpbpc6ZtgdkssmYMBQbUqhW2u5Zn7lZLxm45RmdkNlvGbzhGZ+oWW8ZuuEZn7/Zbxm+4Rmfl1mvGbnhGZ+u2a8ZveEZn4ZZ7zm9QnN/O7OmZq7GZSjcFwC3cF0gfdM4RKPgftTllvSr9FNCWt30bFBF7DmtqMnp3N9FsbRrUDUNp0Qfg+lHRqk1xV1aQohZBFmkF2RNKmRhgt7v9w/YM74v3KmMbczjS/ImfrczjS/IGdqczvz1GLIrxhOvhj+L4Qp9PIPf4koOV+OL2efPtwvx5ezr2vrL8eX83xwdT9qM3rvduzGkN2Cnn5jyK9MT78x5Perp98Y8svY028M+c3t6TeG/Jr39BtDfid8+o0hv0A+/caQ3zZ/4Mbwll6THp9D0Vw5BDfcZ8ghdh1+jhyCu/Mz5BC7aD9DDrFb+dPnEL/CP0MOsfv+M+QQKw54YA5tye32sSnEagymTyFekTB9CvH6helTiFc7TJ9CvDZi+hTilRTTpxCvu5iBn2RVGtOnEK/peGAKlchLRmYQLw2ZPoN4Jcn0GcQLT6bPIF6nMn0G8bKWGTKIVcHMkEGsaGaGDGI1NjNkECvJeWAG+f2D0ZMZxCp7ZsggVgg0wxrE6oZmWINYmdEMaxCrSpojg6CIaYYMYjVPM2QQK5GaIYNYRdUDMyimpUDjc8icJ4d4Fdf0OcRLvqbPIV4fNn0O8WKy6XOIV55Nn0O8TG36HOI1bdPnEC+Ae2AOHWjl1ti9EKujmz6HeNHd9DnEK/SmzyFezjd9DvHav+lziBcKTp9DvKpw+hziJYjT5xCvV3xoDsXph7EZxMoe5yDkoEpyBkKOFVXOQchBDeYMhBwr2ZyBkGMVnjMQcqwgdA5CDupHZyDkWLnpuAwi/+O3HVlFacPK9UWf6G5eS1W/GbiUWKnqJqrskrc1Xt0u3u6GFa7PVth0Q7MItuWLHVRdDttjVbVCi22t3X74WXg7rJdX4J6vuNmfRu3tuO5ow/Ft6RzXGc0cpbXVk2b5bqsvIVQKD1sdupHbUdntSsyriiX9GR62J5SH6KTyhTVOd9Nb3WrkdvC1YaPGUE1SX2MvH/Vhtbo9Vm03K98Pj2JW3SzJIQ4YTKL3Q+N5V1dbD+sH6Xjlfl2aPUvjfVbKPVnLu0GhZcxnj6276pXlTic1UKTGW2KdaR8zzpomjM8wYZxnwvwME+Z5JqzPMGGdZ8L+DBP2WSbIQKRGxls4saDY4zVKq9j6bVaX7gMcIy3CExmxzzfSzEJWx7so6L8S0ErFj4LanxvRingLD9vFUJgfz/mXXktQHPDCFYr0sM9MIuj9swTCrsVpipcx1vKuB5u1RjdNEK25v/8v).

### Expected output

Output in Swift that compiles. Right now the generated code contains many invalid lines of code like:
```
public class  {
    public static let colorsBlue100 = #ebf8ff
    public static let dimensionXl = 4px * 2 * 2 * 2 * 2
    public static let fontWeightsBodyBold = Bold
    public static let exampleShadow = [object Object]
    public static let fontFamiliesHeading = Inter
}
``` 

### Version

0.9.1

**Comment by jorenbroekema** [comment]
Related issue: https://github.com/tokens-studio/sd-transforms/issues/59

We currently by default apply style-dictionary transforms on the transformGroup that are Web specific. You see this in the hex value, font family value, they would work in CSS but not other platforms. 

We basically need more input from iOS developers about how these values should work in iOS context, because I am not an iOS developer myself :). I would be happy to add transforms that work for iOS/mobile context, could you elaborate on how values work in iOS for:
- typography
- border
- shadow
- color
- dimensions

As for the [object Object] and the math expression not getting resolved, not sure why this happens with your tokens, would need to see a reproduction with some tokens and a style-dictionary config / build file.
