### ISSUE TITLE
[Bug]: resolve math with triple multi-value + references is not working

### ISSUE THREAD

**Issue by jorenbroekema** [tokens-studio/sd-transforms#168]
### What happened?

issue when three things are combined:
- math expression
- multi-value (with spaces to separate them)
- token references

```json
{
  "scale": {
    "value": 4,
    "type": "spacing"
  },
  "2xs": {
    "value": "{scale}*1.5",
    "type": "spacing"
  },
  "foo": {
    "value": "{2xs} {2xs} {2xs}",
    "type": "spacing"
  }
}
```

the output of foo, the math is not resolved in the 2nd and 3rd value, we get `6px 4px*1.5 4px*1.5`

### Reproduction

[repro](https://configurator.tokens.studio/#project=jVTbjpRAEP2VCjGZSxiIG31hXGPiZt1H4xpfZOP2QDH0Ct2ku1lnQvh3+wYzMK7KA2nqcqrq9KG6IOOsoPvoSXIWJEGXMoA0kLwVGaZBAt+NwZjW63gdKf4TmbTBaWA8D6FLaCqiCi5qaXK6ISeT59/GogRh0gR+ErxtjFPbLOhGqjanPA3CU3QjsKAHFyXziWvX0ir/TFTpvPYz1vXiSVRBK5RnY5inOx1NSI5SUUYUNSMZqB/PRFCy04mR7T+cxpvmiXKhpt4Y7QhxTz8cH9zBfutXH4SBwD2VCsX9zW3LMlPXEKq5p3XDhYJ7dazwhloPEUcoBK9hIY11k4/mxTZlPqGDAfLrwK6E3ud9mLAby3wzXoE0GCmLY5hYQ7hiOTREkBo1Jmgj8Mb2CRlhsEMgeY65zbxHhJxnMoFSqUYmcbynqmx3Ucbr+C+lU3bZ83I2+WpoDw+kbiqEZ1K1CCNICL9KmpXw1EqlKVCt0B2qUkeYukAkUF1nBhpd1F1aQahjg+ZKbQ1/6UwzYGz18aMuwesxxfu1DrISRQJLW3EF1++h661rbHLudnpw3bpGt6BHfLfZnHJM6wzRcuxks/JMOPFBiVWDQrornisjZfqXlkYWRv13SHIUoc9UmH8b9Kolcj0XW+TC7hz+nH8td4/zMq231u84dfwtBvqca2H5GdrR7BT+L1h2pxlC23s46K5fDcQNo/FWNa36ggUKZJkfxkdvJxw/vupOPCztuV/1ieBcGVDtvWBm6W26dz3yIoTzxuaVNZi+oMfteFX6pP9yJ/rzhXm2XTNS4WRRetUl8CYcTEaQfvM1JKNs7/ZL7xfu1UH+GSENOovfr19Hb8ft9U+8gvMX8XStHs7e/4FqVl3/Gw==)

### Expected output

we expect `6px 6px 6px`

### Version

0.9.10

**Comment by ShaneHudson** [comment]
Thank you so much @jorenbroekema !

**Comment by jorenbroekema** [comment]
You're welcome, this one was quite a pain to figure out haha

**Comment by ShaneHudson** [comment]
@jorenbroekema I've upgraded to version 0.10.3 but it still seems to have the same issue for me? Do I need to provide an extra transform?

**Comment by jorenbroekema** [comment]
If you click the reproduction link I added in the first comment in this issue, it shows to be fixed. If it's still broken for you in some way, can you post the link to a reproduction on your end e.g. in the configurator?

**Comment by ShaneHudson** [comment]
The configurator doesn't handle multiple files very well, which may be the issue. I've tried to replicate here but didn't quite work: https://configurator.tokens.studio/#project=hVRdb5swFP0rV2hSPkSgrbaXZJ0mrer6OK3TXsa0OmCCO7CRbbpGiP++6w9IIGmbJ3w/zj33+DhtcHG5UrrJmIi0+Eu5ih6V4ME6aBMOkAQqJSVNgjXYs4k8kbKxkfdhH9L72kawvCYp47skMKku9Bh98Ajl6lkdnSfISdDaud3yMvqQBOFx0QuzcJodmfAuCIOLq5WiFeGapercXudZvcTsDDvXG2FtB6+cRtzf4D/sMGyRCp6z3fRCRCNTi/Cr32S5jJfHWzrE3179uiQ6F7JSI/1TNd4SiUnClSn8KkVTO4q2KjzU1JLm7NnTz0apbcPK7BvRhcvaY4z98agqZyVVR+TNb6R0EmRUacaJZmYRA/XniUhGttgYjfl4SKRM9MA3HqrPCIuqnJpF0h1Tmsr7m9uGp2aukREVZ1UtpIZ7vS/pDbMZIveQS1HBTJnoKhvCs03CfUMLPeSPXlMFne/77C7KP7pYZatBeGUwEh7HMIqGcMUzqIkkFUVMwCCI2vKElHDYUiBZRjPbeU8pZCJVayi0rtU6jndMF802SkUVvzI64aec55PNFz09+kyquqRgnwQMICH8K1hawGOjNEqgG4kMdYEVZi4QBQznTECjk7lzawjzTtaHZ2cvnaMCJlbtv+AIUQ0tPo8+SAsq1zC3Exdw/Qla9y80kJymnR8cW0d0A7jix9Xq0GOoc0qtxs42C6+EMx8UtKypVO6Kp85IOD5kZWxh3H9HSUZl6Ds1zX72fkWLXE/NFrmyO4c/1R/t7nFelvXW5p2mTr9ZL59Lzaw+PR1UJ/evYN4edggt97D3XbfohetXE42uG/2d5lRSnvplfPVmpPHDu/agw9x+d4tuLYXQBhSzJ8rMfQy548qzEI6JTScjGF7Qw2a4KvwKuv8=

I have however sent my build.js on Slack which may help. You already have all the tokens from our previous discussion.

**Comment by ShaneHudson** [comment]
The configurator doesn't handle multiple files very well, which may be the issue. I've tried to replicate here but didn't quite work. It won't let me paste the link on GitHub.
I have however sent my build.js on Slack which may help. You already have all the tokens from our previous discussion.

**Comment by jorenbroekema** [comment]
Had to fix your link a bit https://configurator.tokens.studio/#project=hVRdb5swFP0rV2hSPkSgrbYXsk6TVnV9nNZpL2NaHTDBHdjINl0ixH/ftQ0ESD/yhO/HueceH6fxLi43StcpE4EWfylXwaMS3Iu8JuYAsacSUtDYi8CeTeSJFLWNvPf7kD5WNoLlFUkY38eeSbV+h9EHRyhXBzU6z5Bjr7Fz2/Vl8KE6xJ4/LnthGs6zQ2Peer53cbVRtCRcs0Q9t5kByoQ443DO6xlubmyAtS28cprwfoP7wH/YIBE8Y/v5dYhaJhbhV7/Feh2uxxs6xN+d9lVBdCZkqSbqJ2q6JRKThCtT+FWKunIUHWhnj9EyiCppxg7dIukktatZkX4jOndZewxxXjipylhB1WgN85toHnspVZpxoplZyUD9eSKSkR02Bpa/P6035Il2pWbeUP2MxKjPuWUk3TOlqby/ua15YuYaQVF7VlZCarjXx4LeMJsh8giZFCUslIlu0iG82Ma8a2igh/zRq6ug7fo+T9QNVboZrkAZjJiHIUyiPlzxFCoiSUkREzAIorI8ISEcdhRImtLUdt5TCqlIVAS51pWKwnDPdF7vgkSU4SujY37OeTnbfNXTowdSVgUF+zhgAPHhX86SHB5rpVECXUtkqHOsMHOBKGA4ZwYanM1dWkOYFxOdHqC9dI4KmFh5/IIjRDm0dHn0QZJTGcHSTlzB9Sdo3L/RQHKedn5wbB3RLeCKHzebU4+hzim1GjvbrDolnPkgp0VFpXJXPHdGzPFJK2ML4/47SlIq/a5T0/Rn71e0yPXcbIEru3P4c/3R7h3Oy7Le2rzT1Om36OVzqYXVp6eD6mTdK1g2px18y93vfdeueuH61UStq1p/pxmVlCfdMl31dqLxw7vmpMPSfrerNpJCaAOK2TNlll0MuePKCx/GxOaTEQwv6GE7XBV+ee1/

**Comment by ShaneHudson** [comment]
Hmm I wonder if the problem is that both objects are called `spacing`. When I tried to change it in your new link, that failed. Obviously it's the output from Tokens Studio so I am unable to change it on the input. Could it be the parser is struggling with both objects called the same thing?

**Comment by jorenbroekema** [comment]
Yes, in your version the token has the exact same name as what it's referencing in the value, so then when you do this reference `{spacing.2xs}` inside spacing.2xs itself, it is creating an infinite loop of referencing itself.

**Comment by jorenbroekema** [comment]
Can you share the repository for me to troubleshoot it manually? Or perhaps create a reproduction repo for me to check?

**Comment by ShaneHudson** [comment]
Ah thanks I appreciate that @jorenbroekema here's a repo that I think will cover everything you need https://github.com/ShaneHudson/design-tokens-replicate-bug 

It's ` --token-semantic-spacing-inset-default` and the similar groupings that is broken.

**Comment by ShaneHudson** [comment]
@jorenbroekema That's incredibly useful, thank you!

**Comment by ShaneHudson** [comment]
I am so sorry... I've just realised that while your recommendations are helpful and appreciated, the issue I was having was due to being on the previous version of Style Dictionary itself!

So for anyone else that may find this, make sure you're on 3.8.0 or higher (of Style Dictionary, not sd-transforms).

**Comment by jorenbroekema** [comment]
Actually, style-dictionary configurator is relying on a browser patch of style-dictionary that's based on 3.1.1 I think, from the top of my head. So 3.8.0 is not a requirement, pretty sure anything on the v3 major will work just fine.
