### ISSUE TITLE
Namespacing transform to target language

### ISSUE THREAD

**Issue by gsouquet** [tokens-studio/sd-transforms#17]
It appears that a lot of transforms output some form of CSS.
However nothing in the transform names indicates that.

I was wondering whether we could namespace the transforms so it is a bit easier to understand what the output is going to be.

- `ts/typography/shorthand` would become `ts/typography/css/short`
- `ts/type/weight` would become `ts/type/css/weight`

That would open transforms target for other platforms like `swift`, `compose`, ...

**Comment by jorenbroekema** [comment]
I think for the typography shorthand, I agree, it seems specific to CSS/web, so I'd be okay with that change.

As for the fontweight, I think the 100-900 format is quite standardized and actually makes it easier for style-dictionary formats to format it properly to android/ios/etc. keynames. Therefore I'm a bit torn on that one, I don't see it as being CSS per say.
