### ISSUE TITLE
[Feature]: Themes example code that is compatible with Token Studio Export to Github

### ISSUE THREAD

**Issue by dcooper-fg** [tokens-studio/sd-transforms#186]
### What feature would you like?

There is a limitation in Token Studio where when syncing tokens from Figma -> Github it's only possible to do so where it writes the single `tokens.json` file in the repo. There is no way to configure it to output multiple files.

The theme and multi-dimensional themes examples are written assuming the export is done with multi-file mode:
https://github.com/tokens-studio/sd-transforms#themes-full-example

It would be great to have an example script that processes multi-dimensional themes from the single `tokens.json` file that the Token Studio export to Github supports.

### Would you be available to contribute this feature?

- [ ] Yes, I would like to contribute this

**Comment by lukethacoder** [comment]
Ran into a similar issue, not super happy with the result but it works.

Takes your giant single `tokens.json` file and generates the same structure as the multi-file export from figma.

```js
const SINGLE_FILE_PATH = 'tokens.json'
const INPUT_FOLDER = './'

const convertSingleFileToMultiFile = async () => {
  const singleJsonFileData = fs.readFileSync(SINGLE_FILE_PATH, 'utf-8')
  const allTokensData = JSON.parse(singleJsonFileData)

  for (const tokenKey in allTokensData) {
    const folderPath = tokenKey.replace(tokenKey.split('/').at(-1), '')

    // mkdir so write file doesn't fall over
    await fs.mkdirSync(`${INPUT_FOLDER}/${folderPath}`, { recursive: true })

    await fs.writeFileSync(
      `${INPUT_FOLDER}/${tokenKey}.json`,
      JSON.stringify(allTokensData[tokenKey], undefined, 2),
      'utf8'
    )
  }
}
```

Keeping an eye out for `style-dictionary` v4, adding browser support and less reliance on `fs`. Hopefully the tokens-studio team will be able to work some magic here to take advantage of those features when it drops.

**Comment by jorenbroekema** [comment]
Multi-file sync is possible in the figma plugin, so it shouldn't block you.

That said, you can also read the `tokens.json` contents yourself, parse it, grab the `$themes` property from it, and pass that into the `permutateThemes` utility. This is more of an edge case and multi-file is definitely recommended over single-file, so I don't think it warrants adding this to the README.
