### ISSUE TITLE
[Bug]: Modifier Value References are not resolved

### ISSUE THREAD

**Issue by DarioSoller** [tokens-studio/sd-transforms#211]
### What happened?

Using token references for example for the alpha modifier gets not resolved, resulting in the alpha value just being missing without any warning/error. This might be related more to issue #198, rather than #164.

Consider following token data:
```json
{
  "core": {
    "alpha": {
      "30": {
        "value": "0.3",
        "type": "opacity"
      }
    },
    "color": {
      "inverse": {
        "200": {
          "value": "#ffffff",
          "type": "color",
          "$extensions": {
            "studio.tokens": {
              "modify": {
                "type": "alpha",
                "value": "{core.alpha.30}",
                "space": "srgb",
                "format": "hex"
              }
            }
          }
        }
      }
    }
  }
}
```

### Reproduction

[TokenStudio Configurator Reproduction](https://configurator.tokens.studio/#project=hVZRb5swEP4rFpuUpCJQrW/pNk3aVO1l0rRO28OoNgeO4BVsZJs2WcR/39kGAiZt89DC3ee78913dxwDpZuMiUiLe+Aq+qsEDzbBMeGEJEEqJCTBhthXI6BlXdCRxMiuLicCI3qgZWMPJsFldJUE4VipD3WnEzVNmT4kQa9u3UMb9v5SUQrp+WP8AaSCmdM3l34gXiivcvubhDMNqHPn6V/DXmNumOBq5sDoJxk8gzCYSmQsP5xVTkPoMhyeQ43ucjSliSw4urpsnzigMMHdASV32ydQuZAV1Q5WwP5Ujv7XTgWT19FL65fR/MM/bRAGEnZMaZC3n24anmqTS+QaMo1VtZCa3OpDCZ+Y1VB5ILkUFVkoI11ng3hxnfDuwJH0Jr9LypW5gyJtd+6Dq8XaVSZW2VoPIGMj4XFMJtKQvOEZqamkFaBNgkIiahsnSSknWyA0yyCzJ28BSCZStSGF1rXaxPGO6aLZRqmo4mdcJ3we89K7+aoPD/a0qksgtuhkMBKSx4KlBfnbKI0p0I3ECHWBCOOXUEUY+vGMRjO/S0tDQ7vNiViWHRwzYGTV4SO6ENVwpNMjVdIC5IYsrccVefeeHF3HDkH6ascHF60L9JrgFd+u16czJnQOYHPsaLPqMuH4SQooa2x8V2KfGQlPsVSGFjkr4TPQDGTYndSQ/aCS0W0JhiLvfLJFDvbZ2ffznyrV2Xk6rTdW73Lq8rfo0+dUC5ufPhzMTt51wfJ4ukNoYw973rWrPnH91USj60Z/gxwk8LS7TIe+nuT4z+vjKQ9L+9yu2o0UQhujqJ1lZtnJMHa88iIk48B8z2gMC/TneigVPmGXY6A523lLRIlGuin0qx/rFxfxxXjjuJFzF7oDdUm165fx6sGgvEWwbViZfaW6cKPLvsYIi0dzDq1JyNm+G4LZRDXqzFN0nUrFdhnEdnAz5IW/xXqAcYhTE8crnUNUQTPxaDGqwLFVUJ7NUVshsUwvobBZxU7Suji8hJSgRPkAX2xqXjCTC65vaMXKw7NQA/sJbFfoM5dk/yAuGYfiOYBxVoJhv9lKjO/muOF74KyBej9XZKBSyWwHfBcfRVUB9/2bfoyRyfE9bOn2tNzuRkQw/eFzwPuOQE+acWo8OS79fug7J7LU9D4axkvVXH1Aj9frsDHv/I3Z/gc=)

### Expected output

Instead of
```css
:root {
  --sd-core-alpha-30: 0.3;
  --sd-core-color-inverse-200: #fff;
}
```
I would exect
```css
:root {
  --sd-core-alpha-30: 0.3;
  --sd-core-color-inverse-200: #ffffff4d;
}
```

### Version

0.11.6

**Comment by DarioSoller** [comment]
Just noticed that as soon as the value on which the modifier is applied to, also is a token reference, it works in the [TokenStudio Configurator](https://configurator.tokens.studio/#project=hVZfb5swEP8qFpuUpCJQrW/pNk3aVO1l0rRO28OoNgeO4BVsZJs2WcR339kGAiZt89DC3c/39+c7joHSTcZEpMU9cBX9VYIHm+CYcEKSIBUSkmBD7KsR0LIu6EhiZFeXE4ERPdCysQeT4DK6SoJwrNSHutOJmqZMH5KgV7fuoQ17f6kohfT8PRZMw3MuX+X296TbzujgNDzZZvwBpJpbf3PpJ+n5PJpSRdZyZANsJ+7PBuDpX8NeYwuY4Grmy+gnjTqDMJhKZCw/nFVOQ+gaGZ5DzdKy4Ojqsn3igMI+dgeU3G2fQOVCVlQ7WAH7UwP6XzsVTF5HL63PFvMP/7RBGEjYMaVB3n66aXiqTS2R0khoVtVCanKrDyV8YlZD5YHkUlRkoYx0nQ3ixXXCuwNH0pv8LilXJgdF2u7cB9eLtetMrLK1HkDGRsLjmEykIXnDM1JTSStAmwSFRNQ2TpJSTrZAaJZBZk/eApBMpGpDCq1rtYnjHdNFs0WaVfEzrhM+j3npZb7qw4M9reoSiG06GYyEBFmcFuRvozSWQDcSI9QFIoxfQhVh6MczGs38Li0NDe02J2JZdnCsgJFVh4/oQlTDkU6PVEkLkBuytB5X5N17cnRXdQjSVzs+uGhdoNcEU3y7Xp/OmNA5gK2xo82qq4TjJymgrHEGuBb7zEh4iq0ytMhZCZ+BZiDD7qSG7AeVjG5LMBR555MtcrDPzr5f/1Spzs7TZb2xeldTV79FXz6nWtj69OFgdfLuFiyPpxxCG3vY865d9YXrUxONrhv9DXKQwNMumQ59Panxn9fHUx2W9rldtRsphDZGUTurzLKTYeyY8iIk48B8z2gMG/TnemgVPuEtx0BztvN2lRKNdFPoV789Li7ii/FicyPnLnQH6pJqd1/GGw6D8vbNtmFl9pXqwo0u+xojLB7NObQmIWf7bghmE9XoZp6i61QqtssgtoObIS/8rdUDjEOcmjhe6RyiCpqJR4tRBY6tgvJsjtoKiW16CYWXVewkrYvDS0gJSpQP8MWW5gUzueD6hlasPDwLNbCfwHaFPpMk+wdxyTgUzwGMsxIM+81WYnw3xw2fHWcN1Pu5IgOVSmZvwHfxUVQVcN+/uY8xMjm+hy3dnpbb3YgI5n74HPA+KdCTZpwaT45Lvx/6mxNZanofDeOlalIf0OP1OmzMO39jtv8B), but unfortunately not in my code. Would be cool to see the sd-transform and maybe the style-dictionary versions that the TokenStudio Configurator currently uses at that moment.

**Comment by jorenbroekema** [comment]
Hi, acknowledged as bug, I'll try to find some time to look into this one this week.

But of a hidden feature (more like a bug, but actually really useful 😅) but you can adjust the version of sd-transforms `import { registerTransforms } from '@tokens-studio/sd-transforms@0.11.8';` and this should work for any package.

However, it does not work for the style-dictionary import, that one is unfortunately hardcoded at the moment and not really possible to dynamically fetch from the CDN for the Configurator's internal usage, although I will consider making that a feature in the future and change this from a bug (unintended feature) to something officially supported. Will also need to adjust the "Eject" functionality to keep into account these versions that the user may specify when creating the eject output.

**Comment by DarioSoller** [comment]
@jorenbroekema Thanks a lot for your answer. For me right now, having the possibility to change Style-Dictionary and SD-Transform versions, would be a very welcomed feature of the configurator. So cool feature idea IMO. As a quick improvement, just displaying the versions somewhere in the configurator, would also already help.

Besides that, I just stumbled over another case regarding this bug, where it is not working correctly. As I mention in my comment before, as soon as you have a token reference as the color value the alpha is applied to, it works in the configurator. I also wrote, that it does not work for me in my project. The reason for this is, that the token definition is spread across multiple JSON files. This then is also [a reproducible bug in the configurator](https://configurator.tokens.studio/#project=rVTvj5NAEP1XJmjS9kKheokmPTUmmupH4xm/2Iu3haFsBZbsLuc1hP/d/QUU6DUxyhdg9u3Mmzdvt/Y47qmQyG8/bqoikpQVIjgIb+3RvGRcwq08ZviRmhXCj5BwlsNM6Ogy7sKzm20B4LbU0Cb9xkkhEsZzAY3b+V6yX1iIpZBVTFko4qXsQDqLzhOGMIj78LKIoSSc5KiyggoCKw1XiEgBOwQSxxi7vbeIELNIrCGVshTrMNxTmVa7IGJ5eKG83j5lPh8psOhJ4iPJywzhgWQVQpfIh98pjVI4VEKqhLLiiqdMFULXBiKAmlqjxMGk9rzWMAB5LHENW8/U2Xq+jRZKDR3Njx9UIZZ32zpETmSUIl/D3FRewNt3UDdusaM7BthlcMwt6Rvd7pvlst+l2ygQneoAjX41i04bjSESUsxK5MIOf+waDY3UELVlEprhZyQxct/tlRh/J5ySXYbaPm8nelnYZ1thOpVICJfpktgbg2iVtprOWknt4swp1tJSeiXurMzrvhvf9OC3zmwWvZRtk6ySZSW/YoIci8i15fA3I93vn9e9JnPz3SyaNWdM2sRqfaLT3MVUD6r9mQ+n9MbVVToztPubwQjVn+d7inJC9+oqYIW6DEzBrSdYxSPlwDX8sFu23tVVeGVQW0+H7nyLLDMi7aFS4LoFK04n/zrS+ekTZ1WpF1Xs9Ih2ZjZZOSb00aIYGSztKprFX4hM7ar5DVW9cIDSKooT/vqp+08NiVFIWhCtmk3186FVNzD8/SHeWcxAdb0ObQWxT9N+3jmp/VaSw78pcrbtw3/oum/6cLnnA3kgIuK0lCGKVxebNv7aFo2yl8CcFJJGYcQyxpdC3VM5ijCj+1SOTeegAyeRrEzJSLmYCs04HoShvzc12zpiHAOzO7heNYPOlM7qonXuKklE5bFvpxkPzhAfMRAVT4g9IAMCMSakyuQofoHzE7xNzWCnosGL1Yj9uAPHb4J4jo9SmUlfOWeKmi6MzQJrurMYjcpZTJPjE8tDKm5Y/nncaZftrN2EWnWaJzeL0umtPvl+9yTu1LEpPp7atH2acWgUGPw2Z2zeTG2up2YtLkau1ivDu/GMn3ZOmYGZ1OTPGOlExWeb1eb15sPk1E68caEH/9JBu15dOmKr4Prvj1WnWfMH).

If you have test cases, then these would probably be interesting cases to automatically test against, what do you think?

**Comment by yanguly** [comment]
@jorenbroekema @DarioSoller I think there is a bug in modifier. I did short investigation:
It's not a problem of multiple files. My analysis indicates that the issue does not stem from handling multiple files; rather, the modifier appears to fail when a value uses a reference to another one (from this file or another).

[Here is the link to the configurator](https://configurator.tokens.studio/#project=rVRdr6M2EP0rI7pSkisCaVdqpdxuVWlX6T5WvVVfmlXXgSE4BYxsc3sj5P9efwEBcpFWu7wA4+OZOcdn3AYcz1RI5E8fDk2VSMoqEV1EsA9oWTMu4UleC/xA7QrhV8g4K2ElTHSb9uHV47EC8Fta6JL+yUklMsZLAcrv/FWyf7ESWyGblLJYpFvZg0wWkyeOYRQP4YcqhZpwUqLOCjoIrLa9QkIqOCGQNMXU731ChJQlYg+5lLXYx/GZyrw5RQkr44XyZvu88/VEgc3QJL6Qsi4QnknRIPSJQvgvp0kOl0ZInVA2XPcpc40wtYEIoLbWJHE0q71uDQxAXmvcwzGwdY5B6KKVVsNEy+t7XYiV/bYeURKZ5Mj3sLaVN/DuF2iVX+zbnQLcMvjOXdOPhu7P2+2wy9CoEL3qAMq81KbXxmCIhByLGrlwhz91jYEm+hCNZTJa4EckKfLQ75WY/kU4JacCjX3ezfRysI+uwvxUEiF8piWxDxbRKe00XXWSusWVV6xrS+uV+VlZtwOb0HIIO2eqzSBlR5I1sm7kH5ghxyrxtDz+caL75zftoMnafquN2nPGpEus12c6rX1Mc9D0VyHctjetrtPZQ/v8ODpC/ReEgW45o2d9FbBKXwa24DEQrOGJduAe/nZbjsHDQ/xgUcfAhD6FDlkXRLqh0uC2A+uebv5NpPfTb5w1tVnUsdsR7c1ss3LM6ItDMTJaOjW0SH8nMner9jfW9eIRyqgobvo3Tzt8GkiKQtKKGNVcqn+eO3Uj2384xnuLWaip16OdIO5R3ecnL3XYSXL5OkXu0r58A9YD6csy5wt5JiLhtJYxih8XSVt/HSul7SWwJJWkSZywgvGt0PdUiSIu6DmXU9N56MhJpKhzMlEuxYw0hRxFYbg2TbO76O2IjJZW363eUDVJqLwODNSNhCkVRo10KXnbdRrZ7iLfj/qCilN3WHUmNEXDM+KmcNTJffoLzc8JJIxjZGtGJx2Nvt/t1OTwxwx8fzPEG3yR2rHmXrtT1LKwXo6cs+9iDKpkKc2uryyPW/GOCO/jlo7Jq6Ne3Sxqr7f+5OfTq7jbscjx5XYWukdNQ5PA6FfdmSU1nyVzam6OxGR0zMr4Ar7jp5NXZmQmffJ3jHSj4neH3eGnw/vZ1TDzxgKHcGma3+6+3SBPNVP/Aw==)

Let's take a closer look at the code:
`{
  "semantic": {
    "alpha": {
      "default": {
        "value": "0.3",
        "type": "opacity"
      },
      "disabled": {
        "value": "{semantic.alpha.default}",
        "type": "opacity"
      }
    },
    "color": {
      "surface": {
        "default": {
          "disabled": {
            "value": "{core.color.blue.100}",
            "type": "color",
            "$extensions": {
              "studio.tokens": {
                "modify": {
                  "type": "alpha",
                  "value": "{semantic.alpha.disabled}",
                  "space": "srgb",
                  "format": "hex"
                }
              }
            }
          }
        }
      }
    }
  }
}`

As you can see from the code, **disabled** uses the reference to the **default**
If we use **"value": "{semantic.alpha.disabled}"** in modifier, then it doesn't work, and we'll have the result:
`  --oaSemanticColorSurfaceDefaultDisabled: #f0f7fc;`
One interesting finding: result for this token is lower-cased, but for **core.color.blue.100** it is upper-cased.

If we use **"value": "{semantic.alpha.default}"** in modifier, then it works:
`  --oaSemanticColorSurfaceDefaultDisabled: #f0f7fc4d;`

**Comment by jorenbroekema** [comment]
> Besides that, I just stumbled over another case regarding this bug, where it is not working correctly. As I mention in my comment before, as soon as you have a token reference as the color value the alpha is applied to, it works in the configurator. I also wrote, that it does not work for me in my project. The reason for this is, that the token definitions are spread across multiple JSON files. 

@DarioSoller I actually identified this bug yesterday as well, see https://github.com/tokens-studio/sd-transforms/issues/217. It is a separate bug though as @yanguly mentions, the references not working on color modifiers is its own bug. Looking into it https://github.com/tokens-studio/sd-transforms/pull/219 , got a failing test to confirm the bug

**Comment by jorenbroekema** [comment]
Update, I had to dive pretty deep into style-dictionary to figure out what's going on with transitive transforms and the resolving of references.

https://github.com/amzn/style-dictionary/blob/v4/lib/exportPlatform.js#L59 the "offending" code is somewhere in this while loop.

Some observations:
- When there are reference chains, this while loop can run more than once until all deferred prop transforms have ran, which means the cycle of two steps, `1. transform -> 2. resolve`, can run multiple times when there are transitive transforms (allows references to be transformed and resolved in order of chain) in combination with token references applying to a token. https://amzn.github.io/style-dictionary/#/transforms?id=transitive-transforms explains this a bit, but it's quite tough to wrap your head around it, or at least for me it is.
- https://github.com/amzn/style-dictionary/blob/v4/lib/transform/object.js#L59 coincidentally also line 59, in this function which is called by exportPlatform while loop, there is an if statement that checks for the existence of a "value" property. Traversing further down the token tree only happens if there is no value property, which means that references further into the token tree (e.g. metadata -> `$extensions.['studio.tokens'].modify.alpha`) never get traversed. Let's pretend for a second to remove the else, and traverse further into the tree regardless of whether we've already found a "value" property key.
- The next issue is now https://github.com/amzn/style-dictionary/blob/v4/lib/transform/object.js#L73 which checks if the token value uses a reference, if it does, then it gets added to the list of deferredPropValueTransforms, to be transformed in the next transform cycle (after reference is resolved). However, our reference isn't inside the token.value, it's inside $extensions somewhere. So we'll need to traverse the whole token to account for that to get it added to the deferred list of props to transform in the next cycle.

So, this is quite a rabbit hole for me to fix in style-dictionary in its current architecture. I might try... but I have also raised an issue to discuss the style-dictionary architecture with regards to references and transforms on a more broad level. In my opinion this use case / issue is more easily tackled in the architecture changes that I propose here https://github.com/amzn/style-dictionary/issues/1032

I'll update this issue if I manage to find an acceptable workaround fix in Style-Dictionary's current structure, but I think I'll then have to look at this again with a fresher mind.

**Comment by DarioSoller** [comment]
@jorenbroekema thanks for going down the rabbit hole and your detailed updates on it!
I think the big challenge with the current architecture is, that `@tokens-studio/sd-transform` is getting to the limits of what is made possible for a transformer within Style-Dictionary. Previously when I relied on the [token-transformer](https://github.com/tokens-studio/figma-plugin/tree/main/token-transformer) I have done the transformation as a preprocessing step for the actual Style-Dictionary build. I still keep to have a preprocessing step, even after the switch to `@tokens-studio/sd-transform`, in which I manually resolve the compositional token references, described in #217 . But as you can imagine, I pretty much rewrote my on token-transformer, in order to resolve these compositional tokens, so nothing I would actually recommend. This also takes into account, that you have to resolve the right token types for the respective tokens being combined within the compositional token.

Another use case I ran into, has been, that you might want to introduce extra tokens, if a certain condition is met, something like i.e. when a token has a specific value. That's also something which is really hard to do or probably not even possible with Style-Dictionary's current architecture!?

As this modifier value references issue seems not to be solved easily and quick, I will most likely add another step to my preprocessing, which resolves the references under `$extensions` deeper in the token object tree. Hoping that I can throw it out one day.

PS: Thanks @yanguly for your example and contribution to this discussion!

**Comment by jorenbroekema** [comment]
@DarioSoller since you're doing a preprocessing step outside the scope of Style-Dictionary to work around the current issue of "references inside sibling properties to the value property are not being resolved", it might be interesting for you to test Preprocessors, which is a new lifecycle hook that you can use to do such processing after token files have been parsed and merged, but before any transforming/resolving happens: https://github.com/amzn/style-dictionary/blob/v4/docs/preprocessors.md (as of [style-dictionary@4.0.0-prerelease.2](https://github.com/amzn/style-dictionary/blob/v4/CHANGELOG.md))

**Comment by jorenbroekema** [comment]
Created a draft PR where I fix this problem https://github.com/amzn/style-dictionary/pull/1069 by allowing a transformer to return undefined, which would defer the transformation until after references are resolved. This is very similar to when the value prop contains references, except now it also would work if metadata that the transformer relies on contains references. Needs a bit more discussion/tests but there's progress on this issue at least :)
