### ISSUE TITLE
"transforms must be an array of registered value transforms"

### ISSUE THREAD

**Issue by ipoly** [tokens-studio/sd-transforms#276]
https://github.com/tokens-studio/sd-transforms/blob/376cbe605b5bd0765ba6b744d2a178078d260815/src/registerTransforms.ts#L212

The `'name/camel'` here will cause an error to be thrown.

**Comment by Xround2303** [comment]
Тоже наблюдаю данную ошибку

**Comment by remypar5** [comment]
I have the same issue. Using:

```yml
@tokens-studio/sd-transforms: 0.15.2
style-dictionary: 3.9.2
```

Both are `latest` at the time of writing.

**Comment by remypar5** [comment]
If `@tokens-studio/sd-transforms` is depending on a specific version(-range) of `style-dictionary`, you might want to add that to `peerDependencies`

**Comment by remypar5** [comment]
I fixed it for now using the following change:

```git
diff --git a/dist/src/registerTransforms.js b/dist/src/registerTransforms.js
index 4ead120b89e8db6a98ccb1ea7513f6609ad37660..ab7e170c84f0a6161c10730909d0f70ddf261a3c 100644
--- a/dist/src/registerTransforms.js
+++ b/dist/src/registerTransforms.js
@@ -182,7 +182,7 @@ async function registerTransforms(sd, transformOpts) {
         name: 'tokens-studio',
         // add a default name transform, since this is almost always needed
         // it's easy to override by users, adding their own "transforms"
-        transforms: [...transforms, 'name/camel'],
+        transforms: [...transforms, 'name/cti/camel'],
     });
 }

```

**Comment by jorenbroekema** [comment]
I added a compatibility table in the README now and upgraded this package to 0.16.0 to be compatible with the latest Style Dictionary prerelease (27).

I used to avoid peerDependencies but I read that they're installed by default now in most package managers, so I'll give this a shot.
https://github.com/tokens-studio/sd-transforms/pull/278
