### ISSUE TITLE
[Bug]: wrong export in package.json

### ISSUE THREAD

**Issue by JorenVerbaandert** [tokens-studio/sd-transforms#285]
### What happened?

The new release does not seem to work correctly.

package.json still specifies `./dist/index.js` while it should be `./dist/src/index.js`

### Reproduction

Install 1.0.0, not able to access the functions in the library.

### Expected output

Install 1.0.0, expect to import functions from the library.

### Version

1.0.0

**Comment by jorenbroekema** [comment]
Ah yes you're right, that'll teach me to run `npm pack` and test it locally when I change stuff about the build process :')
