### ISSUE TITLE
[Feature]: Provide access to original type

### ISSUE THREAD

**Issue by patrickgalbraith** [tokens-studio/sd-transforms#291]
### What feature would you like?

The `alignTypes` function in the preprocessor overwrites the type (see https://github.com/tokens-studio/sd-transforms/blob/main/src/preprocessors/align-types.ts). It would be useful to get access to the original token studio type somehow. Currently we work around this by creating a preprocessor that runs before the token studio one and adds a `originalTsType` property. 

### Would you be available to contribute this feature?

- [x] Yes, I would like to contribute this

**Comment by jorenbroekema** [comment]
I think this makes sense yes, perhaps put it inside the $extensions.studio.tokens namespace since it's vendor-specific metadata.
Feel free to raise a PR!

**Comment by jorenbroekema** [comment]
Actually I'll handle this PR, this one is somewhat coupled to another fix I'm doing for types alignments, and adding props to the studio.tokens $extensions namespace requires changes to @tokens-studio/types package as well.

**Comment by patrickgalbraith** [comment]
@jorenbroekema no worries thanks for the fast response!
