### ISSUE TITLE
[Bug]: alwaysAddFontStyle Affects Font Weight Tokens Incorrectly

### ISSUE THREAD

**Issue by wannesdebacker** [tokens-studio/sd-transforms#298]
### What happened?

I've encountered an issue with the alwaysAddFontStyle option in version 1.2.0 that affects fontWeight tokens. AlwaysAddFontStyle should probably only affect `typography` tokens.

For example we get the following result.
```
--font-weight-primary-regular-weight: bold;
--font-weight-primary-regular-style: normal;
```

### Reproduction

[Configurator Link](https://configurator.tokens.studio/#project=zVXNatwwEH4V4UtacCLocXtpSwiUEgjNoYc6FNka22pkSWjkZN2Qd69+7LW9SzZ0S6HLHuyZb/5nPj9l6Hou9MVP1CrbZE+FKrJaK/cNRNO6ItsQLyL+V2TGio7ZYSELUgtNL5ldSYP8gckegrTIPmnJiyxfat1gRuUcDItsgjznc4AOuOi7Y/6vR8QfRUgPU6AiQ6i04ifV93WCnFriGOOzY1JUxyJNiP+slwcRXq8kxSF/W1AZV+tfrV7w/nopIcZphYw7WKjwz/KwBwId2NvLq15VTmiF/jD9WYrOaOvIrRskXIqo8ZtKaqs7coZBes534rP3hRoNnsjkkjyP6A9O34PC83T3FPm5s0xhrW2HwbJQlJKVNCfvFCeGWdZB8OSFRJuYHamYIiUQxjnwaHkLQLiucENa5wxuKG2Ea/vyotIdPRK6UFOmb/aqzFPjYWuY4n4KxHsyGkVQb4izPeTEN1o3lpl2mCSlthzshtRMon/FlnH9OL6OM4ZtJXsON8yCcl9gwAkdlEw+sgE/cn7lJxczGj37Sb31bfLT8nxRi2bBnJFGdG+rOPTvO2aZGTbN/i5PWGPBWF0Bora4Mlk1am2U+hDQYzpJuFdK0M/F+FCSudTnJaNXiHtsV/ZC8hvm2rS28ZV6GF1sdky8FtsEWSkW85zLGVVILaCWD3Ad3ed7ShS/gJrtoUIbVgk3vGARcpPg/N5gwKnmBZwUCtrxm7YPmLeHLj99B37iDlGhlL/Q+HyIqbTUNibVwtY2JXsJ0mkuagFh7iuA8kdG76Fk5cwTd4sO10LCfnMXxBQgHNAJxcJ9pBH9eGBWsNIbXsSJ52t8mBdzCRoy36HnDHZc5ZPZkVZiruz5Nw==)

Here you see the `fontStyle` being added unneeded. If you remove `alwaysAddFontStyle` the tokens are what we expect.

### Expected output

`--font-weight-primary-regular: 700;`

### Version

1.2.0

**Comment by wannesdebacker** [comment]
@jorenbroekema can it be that this issue wasn't fully fixed?

For example for this setup: [configurator](https://configurator.tokens.studio/#project=zVXNatwwEH4V4UtacCLocXtpSwiUEgjNoYc6FNka22pkSWjkZN2Qd69+7LW9SzZ0S6HLHuyZb/5nPj9l6Hou9MVP1CrbZE+FKrJaK/cNRNO6ItsQLyL+V2TGio7ZYSELUgtNL5ldSYP8gckegrTIPmnJiyxfat1gRuUcDItsgjznc4AOuOi7Y/6vR8QfRUgPU6AiQ6i04ifV93WCnFriGOOzY1JUxyJNiP+slwcRXq8kxSF/W1AZV+tfrV7w/nopIcZphYw7WKjwz/KwBwId2NvLq15VTmiF/jD9WYrOaOvIrRskXIqo8ZtKaqs7coZBes534rP3hRoNnsjkkjyP6A9O34PC83T3FPm5s0xhrW2HwbJQlJKVNCfvFCeGWdZB8OSFRJuYHamYIiUQxjnwaHkLQLiucENa5wxuKG2Ea/vyotIdPRK6UFOmb/aqzFPjYWuY4n4KxHsyGkVQb4izPeTEN1o3lpl2mCSlthzshtRMon/FlnH9OL6OM4ZtJXsON8yCcl9gwAkdlEw+sgE/cn7lJxczGj37Sb31bfLT8nxRi2bBnJFGdG+rOPTvO2aZGTbN/i5PWGPBWF0Bora4Mlk1am2U+hDQYzpJuFdK0M/F+FCSudTnJaNXiHtsV/ZC8hvm2rS28ZV6GF1sdky8FtsEWSkW85zLGVVILaCWD3Ad3ed7ShS/gJrtoUIbVgk3vGARcpPg/N5gwKnmBZwUCtrxm7YPmLeHLj99B37iDlGhlL/Q+HyIqbTUNibVwtY2JXsJ0mkuagFh7iuA8kdG76Fk5cwTd4sO10LCfnMXxBQgHNAJxcJ9pBH9eGBWsNIbXsSJ52t8mBdzCRoy36HnDHZc5ZPZkVZiruz5Nw==)

The italic one is still getting both style and weight.

**Comment by jorenbroekema** [comment]
You mean the secondary regularItalic?

In my PR I did not test for fontweight values that solely have a fontstyle and not a fontweight. I'm actually not entirely sure what the expected output should be in this case, do we just keep it as is:
```css
--font-weight-secondary-regular: 400;
--font-weight-secondary-regular-italic: italic;
```
Like so?

**Comment by wannesdebacker** [comment]
I think I would expect only:

`--font-weight-secondary-regular: 400;`

Because the `-style` also doesn't get appended to to the regular version. I would expect them to work the same.

**Comment by jorenbroekema** [comment]
I think I'm still a little confused. Let's isolate it a bit more, [reproduction](https://configurator.tokens.studio/#project=fVPBbtswDP0VwpdugBMBO3qXDSgKDLsUyGGHuRhoi461OqIhyu2MwP8+ybLjJIf6ZJKP5CMfdc7ED9rw/q+wzYrsXFqAMmuYy6yA2Yr2G3YDRU+Z/fDYmbrM8jXmx34JNWz9LzLH1kuZxfBU2inLM0dHI57c4fFpsLU3bCX0C93MqWfn4eDHjh7NHEE3QuP4BA8SvTt9cT98Le2ScIa1JEwL+pvnV7KyS+Mo0Tvv0ErD7iQxs7RKwY03hy9WQ48OTxQrBSdwP7ODGi1UBKg16TnzQASaaymg9b6XQqmj8e1Q7Ws+qQ9al3Zl+uluyjxtl/71aHVYNYRKPYuJ4QK8GyiHsFo+OuzbcfVU7DS5AhrsJJjSoub3xYQpTxXrbtD0jI6s/0mjrOgYxO4dR/mu9VPQama0VA5KfQ5rCmrVbBtzvDsI4cHVs8y/V92vDiep/ZInbO+od1yTCDu5SblZ1F1Shz5t7Pruarm2o6caTKef0bfp5GZTBZi6XOTcaBNg67+ERG1rVdvJXuVHmA1XoV6pwirxjN/LVYfGdHRf/Lz9Rogm8cZiFDSR/fOGzmAVEvfzYPktPvJFn6Bxogt6YzA/qYVM+pku72z6Dw==)

```json
{
  "foo": {
    "value": "Italic",
    "type": "fontWeights"
  }
}
```

Expected output, at least in my personal opinion:

```css
:root {
  --foo-weight: 400;
  --foo-style: italic;
}
```

Because the value "Italic" for type "fontWeights" implies "Regular Italic" because if the fontWeight itself is not specified then it must be the default which is regular, then when that's transformed I expect it to be split up into weight and style and for the weight to be transformed to 400, so the actual output matches my expected output.

Maybe you can elaborate on your expected output and why you expect it

**Comment by wannesdebacker** [comment]
If this happens in a token with type `typography` it might be logic to do this. But in a type `fontWeights` I would only expect the `foo-weight`. And not have the automatic style in place here.

Or I must not fully understand why it's added here.

**Comment by jorenbroekema** [comment]
I get what you're saying but if there's an "italic" there, simply only outputting the (default: regular) weight means we lose that design decision "italic" in the output. How does a developer make sure that the UI that's using these tokens is italic, and in sync with the design, if it's removed from the tokens output?

**Comment by thomasmattheussen** [comment]
I'm confused. Extending your example a bit gives me [this result](https://configurator.tokens.studio/#project=jVNNi5xAEP0rjZdNwJmGHM0lCctCCIGFOeQQl1DapXZWu6Sr3V0Z/O/pbnV0BhLiyfqueu/1OWE3KE3H30wmyZJzboTIk4ooTzIRrWC/QDtg8OTJF2rVVwetLvMkXeNu7JdwRcb9QF03jvMkhKd0blmA/VvL76j00P1nu9xMSZpYrDU7tKf7h8GUTpNhf4I/QHc9WSdObmzxXscI2FFUljpxx8F7UBf33cfcLAVnsbYU05L9ydEzGj7MCElWB2fBcEW241CZGynFlTcVH4wSPVjoMHTyTkF93E6UYESBApRCFStPiEJRyZlonOs5k7LWrhmKY0md/Mfo3Kybvru5Mp3RxbcejPJQC9+pJ9YhnAlnB0yFh5ZqC30zrp6CrEKbiQpa9iY3oOh1MRf28K1sB4WPYNG4bzjymh2C0L7CyJ+VevBcxY2Wzp6p9x4mz1ZJptL1jcaYBltGmn+uvO+0OLP9tIint9hbKpGZLF+VXAF1U9SCmxHb667kvR2VOehWPYJrZslFU/o0eVFkHLQRsM1fQiw3WOUm2V19SDNeFfIZCyjmPcP3tJtQ6RZvm5+335CikJ02EAidl/31AlZD4QuP8bD0Oj/sC25ODRddsrcN4pNalpl/pss7m/4A), which is inconsistent. 

I guess the way we're using it is through the use of typography tokens.

```
{
  "fontFamily": {
    "primary": {
      "value": "'Merriweather', 'Merriweather Fallback', serif",
      "type": "fontFamilies"
    }
  },
  "fontWeight": {
    "primary": {
      "regular": {
        "value": "Regular",
        "type": "fontWeights"
      },
      "regularItalic": {
        "value": "Italic",
        "type": "fontWeights"
      },
      "bold": {
        "value": "Bold",
        "type": "fontWeights"
      },
      "boldItalic": {
        "value": "Bold Italic",
        "type": "fontWeights"
      }
    }
  },
  "quote": {
    "blockquote": {
      "typography": {
        "value": {
          "fontFamily": "{fontFamily.primary}",
          "fontWeight": "{fontWeight.primary.boldItalic}",
        },
        "type": "typography"
      }
    }
  }
}
```

which gave us this output
```
--font-family-primary: 'Merriweather', 'Merriweather Fallback', serif;
--font-weight-primary-bold-italic: 700;
--font-weight-primary-bold: 700;
--font-weight-primary-regular-italic: 400;
--font-weight-primary-regular: 400;
--quote-blockquote-typography-font-style: italic;
--quote-blockquote-typography-font-weight: 700;
```

don't know if that makes sense to you? This is pretty hard to wrap my head around right now 😅

**Comment by jorenbroekema** [comment]
> I'm confused. Extending your example a bit gives me [this result](https://configurator.tokens.studio/#project=jVNNi5xAEP0rjZdNwJmGHM0lCctCCIGFOeQQl1DapXZWu6Sr3V0Z/O/pbnV0BhLiyfqueu/1OWE3KE3H30wmyZJzboTIk4ooTzIRrWC/QDtg8OTJF2rVVwetLvMkXeNu7JdwRcb9QF03jvMkhKd0blmA/VvL76j00P1nu9xMSZpYrDU7tKf7h8GUTpNhf4I/QHc9WSdObmzxXscI2FFUljpxx8F7UBf33cfcLAVnsbYU05L9ydEzGj7MCElWB2fBcEW241CZGynFlTcVH4wSPVjoMHTyTkF93E6UYESBApRCFStPiEJRyZlonOs5k7LWrhmKY0md/Mfo3Kybvru5Mp3RxbcejPJQC9+pJ9YhnAlnB0yFh5ZqC30zrp6CrEKbiQpa9iY3oOh1MRf28K1sB4WPYNG4bzjymh2C0L7CyJ+VevBcxY2Wzp6p9x4mz1ZJptL1jcaYBltGmn+uvO+0OLP9tIint9hbKpGZLF+VXAF1U9SCmxHb667kvR2VOehWPYJrZslFU/o0eVFkHLQRsM1fQiw3WOUm2V19SDNeFfIZCyjmPcP3tJtQ6RZvm5+335CikJ02EAidl/31AlZD4QuP8bD0Oj/sC25ODRddsrcN4pNalpl/pss7m/4A), which is inconsistent.

Why is it inconsistent? There's 3 tokens (although 2 of them are smudged into 1) in the input, and there's 3 tokens in the output

> which used to give us this output (which is what we're expecting now, but not getting)

It seems like the token names are a bit weird when expanding typography types, I'll need to investigate why it's doing that, ideally you wouldn't get `-weight-weight` and `-weight-style` in the token names, but rather just `-weight` and `-style`, there might be a technical reason for it to be expanded/named in that way, I'll get back to you on this

**Comment by thomasmattheussen** [comment]
> Why is it inconsistent?

Because one of them is expanded into 2 tokens with a different "naming"...

```
--foo-weight: 700;
--foo-style: italic;
```

...than the other one that is just put out as 1 token

```
--bar: 500;
```

Suppose in some component I have to access these CSS vars

```
font-style: var(--foo-style);
font-weight: var(--foo-weight);
```

I can't do the same for the `bar` token because it's just

```
font-weight: var(--bar);
```

that's confusing for people who consume our tokens (and to me, tbh 😅 )

**Comment by jorenbroekema** [comment]
I get the confusion although I'm not sure how I can improve it given that if you have both the weight and style inside 1 token, I have to expand them into 2 separate tokens, and they cannot both be called "bar", hence "bar-weight" and "bar-style".

**Comment by jorenbroekema** [comment]
> It seems like the token names are a bit weird when expanding typography types, I'll need to investigate why it's doing that, ideally you wouldn't get -weight-weight and -weight-style in the token names, but rather just -weight and -style, there might be a technical reason for it to be expanded/named in that way, I'll get back to you on this

[I actually cannot reproduce the issue above anymore](https://configurator.tokens.studio/#project=pVRNb9QwEP0rVi4LUrqROC4XQNVKCCFV9MCBVGgST3bNOnbwOG1Xq/x37MTZxGlZUHuK8ubrzbwZnxKyLRd6/Yu0SjbJKVeM5Umlld1CLeQxTzasBz3cGFGDmWMevQfZosfyZPUVjREPCHaPZpWy6J9tQcoCyoMzEBpR5Uk6ZbHHJiQ5FxdIeTJ4dP7TpRO77yh2e/sf7AzuWgkmQhesv40u6dwhJjTUO/MZyUQ1PluQorxUafR4aaFCS34p/6fe/prs/+7B12AvauQZKX+32mKkYiF1eVjCIbveGWj2x7+zm6FP1zhPThOwDtvSRT083a4QNABj0HqaVDf1Nx9mPI459WenkasuSf0aCbJobq+3rSqt0IrcXbqrFHWjjWW39ijxWvQWx4JVRtdsRR694md49T5XIeDExpSsC94frD6goqvh7DPiV9aAokqbmnxkrrKMRWjK3inOGjBQo8/kQKabnh0rQbECGXCOvI+8RWRcl7Rhe2sb2mTZTth9W6xLXWcXSudqZPpm0WU6iIqPDSjuFGYuU6NJePOGWdNiyqb5jkihDUezYRVIcr+0B64fwm+QCR9L2XK8AYPKfsEjjd7eCPIBjvSR860Tv2cUMjul3roxObVKrSqxWzycpFtT9qr/GBd69sAO6t+F3W8MNkaXSKQNRSHRoOKgYQ7eO9DpM0mwwxjnl1QSLU6oaIXkN+4xHtay/82cWxa/xJMqE6lgomyadTa/lGjzlVuV7IAFFNO+380qVELiMvnidDmSFQq8ygPZn/dgBBQucN039uRqTQ3hYn1HZ+/oPs9klsfX/QE=), there were some patches and I upgraded configurator recently so perhaps I solved it somewhere in the meantime 🤷🏻‍♂️
