### ISSUE TITLE
[Bug]: Expanded lineheight tokens have wrong type.

### ISSUE THREAD

**Issue by wannesdebacker** [tokens-studio/sd-transforms#310]
### What happened?

I encountered an issue where the lineHeight type is unexpectedly converted to a string instead of a number when using the ts/size/lineheight transform in conjunction with expanded typography tokens.

It seems that the lineHeight transform is being applied before the expansion process. This might be causing the lineHeight value to first convert to a string during the transformation (e.g., "600 12px/1.335 Arial") and then pass through the expansion process, which retains the incorrect string format. (could be totally wrong on this).

sd-transforms version `1.2.3`.
style-dictionary `4.0.1`

### Reproduction

[configurator](https://configurator.tokens.studio/#project=zVZdb9owFP0rVqSJTaKEho9N9GXSqq57mDSNSX1o+mBiE8wS27KdLhTx3+d8gZ1Qo+ZlQ0iQ6+OT6+Nzr733pMoQYaOtZNRbePuQhl5CKL7HJN6o0FsAHQL6E3q5NB6LwDNMMlzEQu96PH4XesPTmNrxeujEpudXgMOw4ZSpg/N61oszRQ7OoF+eSezi7Jdnnjg4J5NRP9bATfuxJ+3ESTvtp+rUSTrrRzpzks7fRFr8VMyht2ZULckLtmrC6YtPPH/lXQ3XWzWZjvtQOhWZzftQOntB0IfR2QmmvXJ0rDroJaSztoJeSTrrKniLg0yvrgSkCKN7DBGhseXYjs6ak8UC8s3OGrBSMaJNKdzBlCS7KplfWCojzxPo4XiKhN58PO5g7JMm9PanwChPDmc5mxrsGK2mxEphseQwqleucR2Qwrn6AmXNQxnFjYzm7rQ1N5VqEIeLJ8X/qu/0ssD75nE0OQf+R1KXRg+p/npDT+CYyCKL27uMRoowKvVdRt9kSMqZUGCpdgm+JeUIFDuwFiwFA1lEr9AxPLgJaT1hDxpKcKjRnxX7jam8qq5KvkRXSteXXDORymJmSH0fWNEhCCgCHAqY4oJJBwHjZXYgghSsMIBIF2g5c4kxQCySC7BRisuF78dEbbLVKGKp73h1SJtM37dWOawMhXOu28ACPA5Ocg6GYKB5OZOkAA+e9AYcPtyUWkaMrklsXAXLfsEyEZW78nhsIacrY7U7T3Xb4QJzwSIsJRPSmmItw55UZXmsgsoF8jvkVtt6pYr0O7XI5YDlQ0RS/T5SJDg8g/2muyMta4JmSWIg2gVjPpuwrvNboXZbMDRvLWDF8uUGIvan4pH1f+Nt8vLKJHm5gFgxgbD4qQ+ETF7GPRCkNi7YGQUuaN5vf16DFm2lGteuVSX4zDlIaJRkyHav6aTz21O6U5dF4+oEqqrgTENu2zegY2F+FSzjdRuzbW/KnJEE/YCNyOWjv5W+BVqTBJt1VHxaRwXSRwOhsPFVcaYIAld63qjIsNPeRQpr3bbwGcpIEK58LOdWU27+PnU77uEv)

### Expected output

That line-height is an Number everywhere.

### Version

1.2.3

**Comment by jorenbroekema** [comment]
Yeah this definitely seems like a bug. Will need to investigate, I don't see from a first glance why this would happen and I'm a bit suspicious it might be related to the JS format rather than the transforms

**Comment by jorenbroekema** [comment]
I was wrong, it was indeed related to our lineHeight transform 😅 fixed in next release (1.2.4)!
