### ISSUE TITLE
[Bug]: ts/shadow/shorthand is no longer available?

### ISSUE THREAD

**Issue by con-cis** [tokens-studio/sd-transforms#311]
### What happened?

I'm trying to migrate to SD v4 and got problems with DropShadow and BoxShadows. What happend to ts/shadow/shorthand ?

### Version

1.2.3

**Comment by jorenbroekema** [comment]
They were moved to Style Dictionary itself and renamed: https://github.com/tokens-studio/sd-transforms/blob/main/CHANGELOG.md#100
https://styledictionary.com/reference/hooks/transforms/predefined/#bordercssshorthand

Also make sure you're using the tokens-studio preprocessor https://github.com/tokens-studio/sd-transforms/tree/main?tab=readme-ov-file#usage otherwise boxShadow type isn't aligned to "shadow" which Style Dictionary assumes.

**Comment by con-cis** [comment]
```json
"elevation": {
          "0": {
            "value": [
              {
                "x": "0",
                "y": "0",
                "blur": "0",
                "spread": "",
                "color": "",
                "type": "dropShadow"
              },
              {
                "x": "0",
                "y": "0",
                "blur": "0",
                "spread": "",
                "color": "",
                "type": "dropShadow"
              }
            ],
            "type": "boxShadow",
            "description": "MD2 Elevation 0"
},
```
this is what my token looks like, which worked with ts/shadow/shorthand

```ts
sd.registerTransform({
    name: "custom/shadow",
    type: "value",
    filter: token => token.type === "boxShadow",
    transform: (token) => {
        return token.original.value.map(({ x, y, blur, spread, color }: Record<string, string>) => {
            const formattedX = Number.parseFloat(x ?? "0") === 0 ? "0" : `${Number.parseFloat(x ?? "0").toFixed(2)}px`;
            const formattedY = Number.parseFloat(y ?? "0") === 0 ? "0" : `${Number.parseFloat(y ?? "0").toFixed(2)}px`;
            const formattedSpread = spread ? Number.parseFloat(spread ?? "0") === 0 ? "0" : `${Number.parseFloat(spread ?? "0").toFixed(2)}px` : "";
            const formattedBlur = blur ? Number.parseFloat(blur ?? "0") === 0 ? "0" : `${Number.parseFloat(blur ?? "0").toFixed(2)}px` : "";

            return `${formattedX} ${formattedY} ${formattedBlur} ${formattedSpread}${color}`.trim();
        }).join(", ");
    }
});
```
which works for me. But the solution from SD is not working even with the preprocessor

this is the result I need:
`$elevation-0: 0 0 0, 0 0 0; // MD2 Elevation 0`

**Comment by jorenbroekema** [comment]
[Working example here](https://configurator.tokens.studio/#project=jVRNj9owEP0rI1+2lQJZ7ZFeeqDtqVIljnUPjm3A3cQTeRy6CPHfa8fkU5DdAwjPm2fPs9/jwsg3yuD6L6FlG3YB4DZ8mC71SXiDlrMNXGItVp9Hq7g+ibLRsfa7q8EAp5a3CLfMbAqcHwFF2bhHGNVOC5XQGRgqEkt0d0HO/LnWCVIO691RKPwX2vqea/ZAwoKIBRnLQt6TsqjlQ2q6n3+y4bUGUoFvHWeEK03Smbp7dc5+bl/gW2cEeO4OaDcPX1eWMacPhrx2u+33xsrYR8FLwUmmqtF52PlzqbemRYQ7w95hBU8UqyvVl5++cHsjXKDbEq637q8eX7WlVbJqTmrlnbC0R1dRZHKb5zCpZvBiFdTCiUrHnUIRsBVGIIWFQoNQSquWudMaFErawNH7mjZ5fjD+2BRriVW+cDS33aSfZio/h6HC3Ui0e3Poo5WCRdg4Oc4MH0cwXXF6NM6CQ2qHUhOhowllMtaMVAqf5hsnVxLNstsL+eGwqdODz7bN7nTTLO6c2XDJ+asuRDE4cGy7ojGl+iX88ea9uMwpDJRPTtibUtPyf0kwqDdWDAY9CWdEEXhragXOMh/nFT61tgf2/fezMrf39T8=)
