### ISSUE TITLE
Provide TransformOptions type

### ISSUE THREAD

**Issue by DarioSoller** [tokens-studio/sd-transforms#319]
Currently I am setting up a fresh Style-Dictionary build project on Typescript. I am pretty happy that there even is the possibility to have SD and sd-transform types. I just wondered if we could also expose more of the configuration types, like [TransformOptions](https://github.com/tokens-studio/sd-transforms/blob/ae759783c7f92be6572c29f4f3270459ce7d93d0/src/TransformOptions.ts#L7).

My environment:
```json
  "devDependencies": {
    "@tokens-studio/sd-transforms": "^1.2.1",
    "@tokens-studio/types": "^0.5.1",
    "@typescript-eslint/eslint-plugin": "^7.18.0",
    "@typescript-eslint/parser": "^7.18.0",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsdoc": "^48.10.2",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-sort-exports": "^0.9.1",
    "prettier": "^3.3.3",
    "style-dictionary": "^4.0.1",
    "typescript": "^5.5.4",
  }
```

Further it seems that the `TransformOptions` type might be missing the `expand` property!? So when I am looking at the code of the [Style-Dictionary Configurator](https://configurator.tokens.studio/#project=5Vvfj6s2Fv5XUO6uuruaJGDAwOzLalV1d7Uv1b0PVdVUlbGPE/cSHGFym3SU/73mRzLAhBCYsdR2Mg+j2Ob77OPzcWzH52mm8j0TcvGzkunscfa0Si1rNWNiC6kSMl3NHq2yrChVlCTQKCnKvpBkX5atZmg1e3iuyI+7ulyJX0W6Xs2qutPDGe6g+rG83WEkmtr2oz1dxrM4qJP1D6tRUA7qNJJsy+4iU9u3IEvWd5Ft2VuQHZK7yJL1K8iKfxWjrtoRWtY1/OyWY7Snso/vDDrRSfS8jUW+0yP0JI1FvnP69YyMRb5zrg/JeGvsk1zML3B3CWUcY6OWgaKZ2OX162o1+17uLUpSa0O+gFV2ZZeAVTIrS6QWsZTG0EU1mpXLz5AurI9AmLWVGVgytfINKHi0Nnm+U4/LJZNULcp2alG9MpfkCxEJiROYV+XLGq7++qFhhHm76qoSYpkxyD4SJvaq/dq94bRej53aYGNcKpyEeMuVHDwJ8j4famJUbtQq6VdFm/xN3Ckrwd7Km6oOzivQs09VTPP5uRuVfa47FJWJzNquFCeEfu635ge7/PRYrMR7OU+/bER+Y4Y+8PIzDnOdkWMH0in61Sh5QRNwwmmD5gbRM1XRCA0gA+OIB1OQ3SFkBCG3pyB7A8g0Zj5MQvYHkIlNgE5CxgPIgRPaEZ6CHAwge8T3cTgFORxARswNvEnI0QCyQ5CN7vfnroIyYOME9FS9Lhb6wYX2gdMQc6v2L3DIq9itOhxlAKu2GOfY16kv3/WSCX68UtWmTsR6o3la5FeGYi+8q02KIFw32ajk2XgtE774cprwzvhTGdM1bUz3HRkTmTam946M6Zg25lAw5D7WfwaC4R9hmhjJPv8uZil4P7Y0/voI348tjce16P3Y0syCq7uolRlJ1zB2Y8j1xnDShmVoY8gBYjpp8T+0MeQxc0NmYmPIMWH+pIjlD26Tw8jFBmLhB8ZwjCbN4NDGkNo+Ro6JjWFEPTQNeWhjGMSu58DkjeERkkT+Ml5D3JSGOI25EQ1p1YeRGQ2B7YMRDVEaebERDeFInzaZ0FAcBJHDjWgo8ImDjWjI85BjT9bQOgNIx0rI1hLyTEiIYo6Zb0JCEQEceyYkhEPmRo4JCXlhHAehCQm5ofbGyISEEA99nxg5nwxw4EUmJISQ77lssoRyIMlIBQEulnImFBQj7gMxoaDQAcyMBCGPM4caWci5YYwINaIgJwoi34iCaECC2IiCQh+wkYUccj3w0WQFxS9/GB1UUMxDzo0oCMDlRrZCkU0ZNxOD3NgFZiQGoSgCx4yCQkSNLONQjGlsG1EQ9VGIjCiIeO6I49eugkTKxFqO15BnRkPUZYSDCQ0RN54YOYc0FPCIciNRCOMApsXkIQ35BAcsNKEhj/pObGQr5Ok9f2Sb0JBLXYzjyRra7bNdMvpIjnDfjIYgYiFnJjSkz6CoGQ3FQeRNi3BDGop4QMxoKLR9woys5PSGE1MjR3K+79KImNCQ57luQKZrSKSfxyqIawUFJhTEgQWATCiIx3qJASYUxHGoT0XNHGpjj5g51Pb1gpmaUFAcuig0spKLAoQxM6GgwEaeH41VUPHvfNtRFjds8+YvWqvZy4Pu5rVU+689lxIvUF2h3rrk7Y+H24j1ph8wuhuwaQYu0/wbshWJgPbVzw0Q1r5o3+H7X5pD1sPYRu2OI5bs2I/7UcYyl2OAm+NJRAr/heJCyMjhOP3z28IcNxjHG4XaGgnk2sCfruQ7MOBkn+T9rH03cjuQ3aGIlGZAFNzwWqffbQfAGQyCz/1x2E1r7UhG1hnZba4ZbOP0k7p9aUgvEV/oEfXDIjwWtqvK7/q9+COs9wnJbmjo3KBXRN/1+XNN8W+Z3JipqnY8eCEWk50v8N+0591J+SR+7b4nb/jW0+WRxQYVCVDOAvk32Gv0MX7WpHBfQeHeR+G9gsK7j8J/BYV/HwV+BQW+i6JwxJJkPMNAQMHjEW9msb3ss70IJxjmZhLeNRJ8P0lThXAg2yKRRW0Iay3XGoyNXhyuRcRjVdhOhtLn49l5pdeqUDsduNg1nHqZWQ6xvpxVZKIsovbtrObgRJrqQFb3vWvDZrbRodlIW+A0e5hlsBaqCIRff7NPaZFxpBY/q9njTGx3MsutT/kxga9FWUOyo8UzubW+UkXpnF2Kv/rnKq0feLLOkNapbv2v6hLYvE4zUmyeZyRVXGZbVTy5SpdLq1X6YKGUWUVc20KBpAstWeZDqTIPKgaLMKYDf/HkJwCryGZ6zm1ai3yzjxdUbpc3qFfpuad/64zyoZpuOOxIyvTcWxppJ5Uoqh+tPNvDg6UNK8ugezyXVNlS52+VM1Xf6vmAA032DL4lGaT5/+Goe8xJokBXnv6u7aCng8qUi3UnFVrJfVZdYvvhor/nlOlqOn88L1oy2GWSglJ14tXlkZYlOg8lJK9M0vR9qrr6u9juP5nc7yq36sA2vX8vEvYtyTe1/xVflxp02WrFRQLNjhafxh6tWuepXKTkOR3upy8kE0WimlqUnXxoty96SPJ626b5Lq2b1/8uV/x+bL4RClGcfgM=) then the second parameter of the sd-transform `register()` function, which should be the TransformOptions object, should have an `expand` property:
```javascript
import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

// sd-transforms, 2nd parameter for options can be added
// See docs: https://github.com/tokens-studio/sd-transforms
register(StyleDictionary, {
  expand: { composition: true, typography: true, border: true, shadow: true },
  excludeParentKeys: false,
});
```

I am aware of the expand feature [being moved from sd-transform to Style-Dictionary](https://github.com/tokens-studio/sd-transforms?tab=readme-ov-file#using-expand), but it still seems to be possible to pass a TransformOptions object with an `expand` property to the sd-transform `register` function.

I would be happy about every tip or additional clarification with this!?

**Comment by DarioSoller** [comment]
@jorenbroekema I am using or want to use it like this:
```typescript
import { register, TransformOptions } from '@tokens-studio/sd-transforms';

const sdTransformOptions: TransformOptions = {
  expand: { composition: true, typography: true, border: true, shadow: true },
  excludeParentKeys: false,
};
await register(StyleDictionary, sdTransformOptions);
```
In general I think it would support a much more flexible usage of the public functions like sd-transforms' `register` function. What if someone wants do dynamically generate `TransformOptions`. He would have a little bit more code around that and typings would definitely help here, also for future changes like we experienced with the `expand` everyone would be much safer, right?

**Comment by jorenbroekema** [comment]
Yeah that makes sense, I'm convinced, PR welcome!

**Comment by DarioSoller** [comment]
PR change is a one liner, but I have a few issues with the tsconfig.json and the husky setup.
1. `tsconfig` should exclude the `dist` folder. Otherwise when rebuilding locally multiple times, it will lead to an error, cause the `tsc` command tries to also transpile the type definition files within the `dist` folder.
![Bildschirmfoto 2024-10-24 um 16 54 50](https://github.com/user-attachments/assets/0f903cb7-90f0-40d1-a8f3-bdf08d7cf7c2)
2. The husky precommit hook leads to the following error:
![Bildschirmfoto 2024-10-24 um 16 57 27](https://github.com/user-attachments/assets/4c4db60d-720c-4410-8ac6-c224863e4cb0)

@jorenbroekema I fixed the tsconfig locally, but I would not make it part of this PR. For the husky error I could need some help. Any idea here?
