### ISSUE TITLE
token-transformer use

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/sd-transforms#32]
Does this mean we can forego the use of [token-transformer](https://github.com/tokens-studio/figma-plugin/tree/main/token-transformer)? Or is it meant to be used in conjunction somehow?

**Comment by six7** [comment]
My goal with this one is that you no longer need token-transformer. The new transforms also include a way to pick up themes dynamically and output correctly.

However there's still some cases that we can't handle with this one yet, namely expanding tokens like typography into individual tokens.

**Comment by sschiffer** [comment]
@six7 does it make sense then to create issues in this repo for features that we'd love to see? Specifically, the `sets` and `excludes` from token-transformer cli (which worked nicely when using a set as "treat as source" in figma). 

We do have a global token set just including raw tokens, so called "options". Which we don't want anybody to use directly. All other sets are built on top of it and just include references. And I basically want to publish different versions of my semantic tokens based on target platform or channel (Web, app, docs).

**Comment by six7** [comment]
> @six7 does it make sense then to create issues in this repo for features that we'd love to see? Specifically, the sets and excludes from token-transformer cli (which worked nicely when using a set as "treat as source" in figma).
> 
> We do have a global token set just including raw tokens, so called "options". Which we don't want anybody to use directly. All other sets are built on top of it and just include references. And I basically want to publish different versions of my semantic tokens based on target platform or channel (Web, app, docs).

Oh, yes, definitely! Please create issues for those! 🙏

**Comment by hongkiulam** [comment]
How does this package replace token-transformer? As far as I can tell, the transforms in this package are still geared towards receiving a Style Dictionary input (provided by token-transformer), or are we talking about long term goals?

**Comment by jorenbroekema** [comment]
Correct. Style-Dictionary 3.0 provides a feature called Parsers, which allows you to customize how you parse tokens (any format, theoretically) into Style-Dictionary input. Currently, we are planning to:
- Deal with tokenset parent keys exclusion, to fix broken references
- Explode/expand composition tokens into separate tokens

This should cover most of it.

**Comment by six7** [comment]
> As far as I can tell, the transforms in this package are still geared towards receiving a Style Dictionary input (provided by token-transformer), or are we talking about long term goals?

The plugin itself already outputs style-dictionary capable .json, the only thing you need to look out for is to export to multiple files

**Comment by jorenbroekema** [comment]
> Correct. Style-Dictionary 3.0 provides a feature called Parsers, which allows you to customize how you parse tokens (any format, theoretically) into Style-Dictionary input. Currently, we are planning to:
> 
> * Deal with tokenset parent keys exclusion, to fix broken references
> * Explode/expand composition tokens into separate tokens
> 
> This should cover most of it.

Both of these are now supported (since a while now actually), so closing this one

**Comment by thomasmattheussen** [comment]
The one thing I'm still using token-transformer for is for creating theme files from the different sets defined in $themes.json.
`npx token-transformer themes --theme`. It seems rather difficult to recreate this behavior in `style-dictionary`

**Comment by hongkiulam** [comment]
It would be great if there was some documentation on these recent changes - the current documentation still points to `token-transformer` https://docs.tokens.studio/sync/github?ref=addprovider#7-how-to-use-tokens-stored-in-github-in-development

> > Correct. Style-Dictionary 3.0 provides a feature called Parsers, which allows you to customize how you parse tokens (any format, theoretically) into Style-Dictionary input. Currently, we are planning to:
> > 
> > Deal with tokenset parent keys exclusion, to fix broken references
> > Explode/expand composition tokens into separate tokens
> > This should cover most of it.
> 
> Both of these are now supported (since a while now actually), so closing this one

Regarding this, my `tokens.json` gives
```json
{
  "global": {...}
  "admin": {...},
  "$themes": [],
  "$metadata": {
    "tokenSetOrder": [
      "global",
      "admin",
    ]
  }
}
```

Which doesn't work out of the box with Style Dictionary, it does with `token-transformer`
