### ISSUE TITLE
transformTypographyForCSS function

### ISSUE THREAD

**Issue by ajuhpark** [tokens-studio/sd-transforms#50]
transformTypographyForCSS function:

```
function transformTypographyForCSS(value) {
    if (value === undefined) {
        return value;
    }
    const { fontWeight, fontSize, lineHeight, fontFamily } = value;
    return `${fontWeight} ${fontSize}/${lineHeight} ${fontFamily}`;
}
```

The transformTypographyForCSS function above currently compiles the variable to something like this: 

`  --heading-1-light: Light 38/46 Proxima Nova;
`

This is using the original variables before they’re transformed but is it possible to use the variables that are returned from the transform functions? For example, the line would show up as ‘—heading-1-light: 100 38px/46px Proxima Nova;’.

**Comment by jorenbroekema** [comment]
Can share the typography token as you have it in JSON, so I can reproduce this behavior?

**Comment by ajuhpark** [comment]
Yes, here's the token for Heading-1, Light.

```
"Heading 1": {
    "Light": {
      "value": {
        "fontFamily": "Proxima Nova",
        "fontWeight": "Light",
        "lineHeight": 46,
        "fontSize": 38,
        "letterSpacing": "0%",
        "paragraphSpacing": 0,
        "paragraphIndent": "0px",
        "textCase": "none",
        "textDecoration": "none"
      },
      "type": "typography"
    }
}
```

Hopefully, that's what you're looking for. My json file can be found here: https://github.com/ajuhpark/token-example-css/blob/main/tokens/input.json.
