### ISSUE TITLE
transformer ts/color/hexrgba does not apply to borders

### ISSUE THREAD

**Issue by C3PablO** [tokens-studio/sd-transforms#52]
https://github.com/tokens-studio/sd-transforms/blob/ec8d0f32be7158f730e6acdc692c5a0cadaab25e/src/registerTransforms.ts#L47

This transformer only works for color tokens so:
`{ ..., value: "rgba(#FFFFFF, 50%)" } => rgba(255, 255, 255, 0.5)`
`{ ..., value: {..., color: "rgba(#FFFFFF, 50%)" } } => rgba(#FFFFFF, 0.5)`

In my project, I changed the transformer to the following as we need to perform this transformer on border tokens:
```
StyleDictionary.registerTransform({
  name: "ts/color/hexrgba",
  type: "value",
  transitive: true,
  matcher: /** @param {DesignToken} token */ (token) =>
    (typeof token.value === "string" && token.value.startsWith("rgba(#")) ||
    (typeof token.value === "object" &&
      typeof token.value.color === "string" &&
      token.value.color.startsWith("rgba(#")),
  transformer: /** @param {DesignToken} token */ (token) => {
    if (typeof token.value === "string") {
      return transformHEXRGBa(token.value);
    }
    return { ...token.value, color: transformHEXRGBa(token.value.color) };
  },
});
```
It would be nice to support composed tokens as border

**Comment by jorenbroekema** [comment]
I think this also applies to shadow object values. I agree it would be good for this transformer to match any color token, whether the token value is a color itself or whether the color is nested inside an object.
