### ISSUE TITLE
Alias tokens that reference typography tokens are undefined

### ISSUE THREAD

**Issue by sofiamichel** [tokens-studio/sd-transforms#70]
When using typography alias tokens within component tokens, the output variable is undefined.

Example of our typography token structure:
```
{
  "font": {
    "heading": {
      "xxl": {
        "value": {
          "fontFamily": "{font-family.cera-pro}",
          "fontWeight": "{font-weight.700}",
          "lineHeight": "{line-height.1}",
          "fontSize": "{font-size.9}",
          "letterSpacing": "{letter-spacing.1}",
          "paragraphSpacing": "{paragraph-spacing.1}",
          "paragraphIndent": "{paragraph-indent.1}",
          "textCase": "{text-case.none}",
          "textDecoration": "{text-decoration.none}"
        },
        "type": "typography"
      },
```
In the config file, I use the `@tokens-studio/sd-transforms` package to convert typography tokens into shorthand so that it doesn't just return `[object Object]`. Example of a variable I get after running style dictionary:

```
$font-heading-xxl: 700 64px/1 CeraPro;
````
This all works great, until I have alias tokens/components that reference the typography tokens. 

Example of an component-specific token that references the alias typography token:

```
{
  "balance": {
    "type": {
      "title": {
        "value": "{font.paragraph.sm}",
        "type": "typography",
      },
```
I've tried dozens of custom transforms to try and see if I can manipulate the output, but no matter what I do I get this:

```
$balance-type-title: undefined undefined/undefined undefined; 
```
If I **dont** use the shorthand transform from `@tokens-studio/sd-transforms`, then I get:

```
$balance-type-title: [object Object]; 
```

If I manually change the component's JSON file to have a type of "font" instead of "typography", it works, but manually changing all of the component JSON files is not a feasible solution and I have not found any other way to get usable output.

**Comment by jorenbroekema** [comment]
Thanks for raising this issue, [I've reproduced this](https://configurator.tokens.studio/#project=rVJNb4MwDP0rKMeK0U2TOqm3adM+bpN62GFUUwoGwmgSJaGiQ/z3JQRKaGk1acsBHPvZ8fNzjSJGE5IGuWQULVEdUs8LkWSliCBES+/DOIxrNpvPAsW+gMoWHCITWfs2gRdYJUxspcmp+5xIunfjUQJTaYDPgpXcBLWvLXolVRkTFiJ/QHMBCaksSsaj0KYkRfyGVWaj7XWu35uPUAkpQDo0zKkH00BikIpQrIihZEp97rAgeKMTg7Z/f4w3zWNloea9A9oOxJ6mN9fWaPx+JPnfJjJJO/8H1gPp/DLnHO+wjAThag5ycZG0+elPg3xkqbj7MyxbwqgarU0GOCY0PRpUVRUjj9d2XZRw5O1LPuEtKfa26XtNzlvpQU9Qo+odSJp19O6ur08wBaHw4mBuJqusyDfY+O2CV6dFQCkQK46jjtpUHY4FTgXm2W9xrzQGerYtBZV6wLJrizIKk5BHiJhwdsECHWF9d+Zqz7uC2mJtF/sB3bja+73A7EjLg24hqs3sgk7yQIvcjHb5/GvtZjU/) and marked it as a bug.
