### ISSUE TITLE
tokens中的继承关系，没有在css中体现出来 (The inheritance relationship in tokens is not reflected in css)

### ISSUE THREAD

**Issue by fengchuanBIG** [tokens-studio/sd-transforms#72]
像这种toknes的：rgba({neutral.neutral-10},0.4)，会变成rgba(22, 24, 23, 0.4),这样不是我想要的，我想要的是和渐变色一样的继承关系，比如linear-gradient(180deg, rgba(var(--green-green-6),1) 0%, rgba(var(--green-green-7) ,0) 100%)，纯色为什么不可以呢？

**Comment by jorenbroekema** [comment]
You probably need the option `"outputReferences": true` in your SD config.

See for example this:
https://configurator.tokens.studio/#project=hVJta8IwEP4rJUNQibUOhM2vA/d17OsqI23SmlmTkhfZKP3v6yVqU930oCV399yT5+7SoFyKgpfxl5YCrVCTiihKkZZW5SxFq+gDAhCaTufT2MgdE9qBUwSZDfYFdUVMIdVeQ01zqsl16EPEKCI0AF+VtDUku5gjnWljKZcpwj26Vqzg3x6l6SCVWV7RN2K2PuvceXfffIAqeMV00AZY0x8BQpk2XBDDoSWg+jwQxUnWFcZOPx7iQTwxHgr3ndFXSFkD6XAC55w1tTXvrGCKidxrNMqyENf2zvm48Qfnd78WYeTnFq6m32MuK6kGK8mIZhc7KRX5uRCZooqXW3MlPUUHUlnmu394ceYfwlEnDjn2jHK7v0Py7Ox/EkrU7g7FwtmA4nRsg8egGL1qM6RZr5POepqwtpDyVm3jBh3DcGMYZ+zG1/7NlRF1i6vighE162goZ8KMF08JZSWOVJmRcXhRp6nFi0mUjI7Jx+USn75kEi2SZDQJJFw+nfYX

Note that this doesn't work well together with Math expressions, due to this issue: https://github.com/tokens-studio/sd-transforms/issues/13

**Comment by fengchuanBIG** [comment]
我就是这样配置的
const { registerTransforms } = require('@tokens-studio/sd-transforms');
const StyleDictionary = require('style-dictionary');

registerTransforms(StyleDictionary);

const sd = StyleDictionary.extend({
    source: ["tokens/**/*.json"],
    platforms: {
        js: {
            transformGroup: 'tokens-studio',
            buildPath: 'build/js/',
            files: [
                {
                    destination: 'variables.js',
                    format: 'javascript/es6',
                    options: {
                        "outputReferences": true
                    }
                },
            ],
        },
        css: {
            transforms: [
                'ts/descriptionToComment',
                'ts/resolveMath',
                'ts/size/px',
                'ts/size/letterspacing',
                'ts/size/lineheight',
                'ts/type/fontWeight',
                'ts/color/hexrgba',
                'ts/color/modifiers',
                'ts/typography/css/shorthand',
                'ts/shadow/shorthand',
                'name/cti/kebab',
            ],
            buildPath: 'build/css/',
            files: [
                {
                    destination: 'variables.css',
                    format: 'css/variables',
                    options: {
                        "outputReferences": true
                    }
                },
            ],
        },
    },
});

sd.cleanAllPlatforms();
sd.buildAllPlatforms();

但是转换rgba({neutral.neutral-10},0.4)还是会变成rgba(22, 24, 23, 0.4)，好像透明度不能转换是吗，  我是两周前进行转换的，这两周有了新的更新？

**Comment by jorenbroekema** [comment]
I ran your code and got a different outcome, e.g. tokens:
```json
{
  "color": {
    "base": {
      "foo": {
        "value": "{color.base.gray.light}"
      },
      "bar": {
        "value": "linear-gradient(180deg, rgba({color.base.foo},1) 0%, rgba(255,255,255,0) 100%)"
      }
    }
  }
}
```

Gives me this output, when running the code snippet you posted:
```css
/**
 * Do not edit directly
 * Generated on Tue, 28 Mar 2023 17:42:08 GMT
 */

:root {
  --color-base-gray-light: #CCCCCC;
  --color-base-foo: var(--color-base-gray-light);
  --color-base-bar: linear-gradient(180deg, rgba(var(--color-base-foo),1) 0%, rgba(255,255,255,0) 100%);
}
```

Is it possible for you to reproduce your problem here: https://configurator.tokens.studio/
and then send your URL here?

**Comment by fengchuanBIG** [comment]
I use '--sdColorBaseBar' in css, it does not work. Please take a look. Thanks.
![IMG_4518](https://user-images.githubusercontent.com/35793306/228711608-159d6f29-9fb5-4840-b56d-6911e444ec37.jpg)

**Comment by fengchuanBIG** [comment]
Can we translate 'rgba({neutral.neutral-10},0.4)'  into 'rgba(var(--neutral.neutral-10),0.4)'?

**Comment by fengchuanBIG** [comment]
所以我会将 var(--neutral.neutral-10) 变成   r,g,b   这样的形式，因为--neutral.neutral-10这个名称没有任何意义
