### ISSUE TITLE
Treat certain token sets or json files as source only

### ISSUE THREAD

**Issue by sschiffer** [tokens-studio/sd-transforms#75]
As within the figma plugin, it would be great to specify certain files or token sets as "source" only. 

In our case we have a global token set (`global.json`) which includes all potentially allowed design options. These tokens are non-semantic, don't use any references but just raw values. 

Then there are multiple token sets for different "channels" (target platforms) like marketing website, application, documentation. These sets contain the so called "decisions" and use references only. In the end, I'd like to compile or build one set of tokens for each of these channels without any of the global tokens. 

This used to work nicely with token-transformer, but I really appreciate the effort to create a style dictionary transformGroup. This feels much more in line with the intended usage of style dictionary.

**Comment by jorenbroekema** [comment]
You can use filter options on your formats to filter certain tokens e.g. by category, [here's an example](https://www.style-dictionary-play.dev/#project=pVLRToMwFP2Va32YLgTUJT5g5uN89d0upkCZVdaS9rJsIfy7vcA22KJLtA9we+5pz7kcapYanatV+OlYzOS2NBYhk7moCoSaawBnKpvKGN44m06jaYjmS2rn+UZztgyIUhYCc2PXLu6OAKTuWAOgFdoR4cWaqoyBM9/nLNj3SytztSXcZQM4qVSRvQr8oE67ify5aMDIVSEdWev3cNTs2yhtDDet51uYP0NbhQLRqqRC6cJUoFwZu4Or+XySGisnwfCKTDpUWqAymly8b4RVIino4GiEVs5PKDCGCbk8EIf3NYd62VcdQs/miWsWMLIQpaYwdvilfTY1t0TlLYMz+ry2u4Mgzx9hhCZFJU9Agu/PMEI3omdzdn3n12JB052QcFf2nF5xSGiCsc7DRZ2ZX//XmV3UefTrDzrHzaHsi/bV+LScXAuNKo1yY37Ka885yUzp3JxFNnBdU85h9ydQkuFDM5rgF/djl803) .

In the example, I have some core tokens and some semantic tokens, if I don't want the core tokens in the output but only the semantic ones with their resolved values, that's how I'd do it. 

Here's another example of an SD config where I dynamically/programmatically create the output files:
- CSS variables for my core/base tokens ('colors', 'typography', 'spacing', 'radii')
- JS variables for my core/base tokens + my button tokens, as separate files per category in the correct folders, very useful for component tokens that need to be outputted on a per component basis
