### ISSUE TITLE
Format android/resources always return string tag

### ISSUE THREAD

**Issue by ptu14** [tokens-studio/sd-transforms#76]
For token: 

```json
{
  "black": {
    "value": "#000000",
    "type": "color"
  },
}
```

config: 
```json
  "platforms": {
    "android": {
      "transforms": ["name/cti/kebab"],
      "buildPath": "build/android/src/main/res/values/",
      "files": [{
        "destination": "style_dictionary_colors.xml",
        "format": "android/resources"
      }]
    }
```

i get 
```xml
<resources>
  <string name="black">#000000</string>

</resources>
```
instead of
```xml
<resources>
  <color name="black">#000000</color>

</resources>
```

If i change token format to CTI, it's work fine. How to fix this?

from what i can see, the problem is hardcoded [prop.attributes.category](https://github.com/amzn/style-dictionary/blob/main/lib/common/templates/android/resources.template#L32) in the android template. I can se hardcoded `prop.attributes.category` in other templates too.

**Comment by jorenbroekema** [comment]
Yes correct, see https://amzn.github.io/style-dictionary/#/transforms?id=attributecti

You need something like:

```js
{
  "category": "color",
  "type": "background",
  "item": "button",
  "subitem": "primary",
  "state": "active"
}
```

where the category must be `color` in order for it to output `<color>` in the android template.

Seems like this is intended behavior from Style-Dictionary, but if it's not as expected or undesirable, I'd create an issue on https://github.com/amzn/style-dictionary/issues
