### ISSUE TITLE
[Feature]: Add ability to inherit metadata props from parent group

### ISSUE THREAD

**Issue by jorenbroekema** [tokens-studio/sd-transforms#87]
### What feature would you like?

Allow metadata props to be inherited from parent token group:

```json
{
  "brand": {
    "type": "color",
    "color": {
      "acid green": {
        "value": "#00ff66"
      },
      "hot pink": {
        "value": "#dd22cc"
      }
    }
  }
}
```

This means it's no longer necessary to add the type to every individual design token.

### Token type

It's a bit tedious to put the "type" prop on every token, especially for core/foundation tokens, where you may have many tokens of the same type grouped under the same token group.

This is currently also spec'd here https://design-tokens.github.io/community-group/format/#type-1

### Options used in transforms, through token metadata

We're currently looking into adding a `ts/size/rem` transform, see https://github.com/tokens-studio/sd-transforms/pull/80
`rem` and `em` however, are dependant on some base font size. Since this changes based on context, I think it would be cool if tokens could contain this kind of context themselves.

For example, the metadata about spacing could be set on the button token group as a whole:

```json
{
  "button": {
    "fontSize": {
      "value": "24",
      "type": "fontSize"
    },
    "padding": {
      "value": "24",
      "type": "spacing"
    },
    "$extensions": {
      "studio.tokens": {
        "spacing": {
          "unit": "em",
          "base": "{button.fontSize}"
        }
      }
    }
  }
}
```

which would result in a value of `1em` for the `button.padding` token, after running a transform on this. Meaning that if the fontSize changes (e.g. if it's a variable), the button padding will change with it due to using `em` unit. And this would go for any button property that's using some kind of dimension-type value, since this metadata exists on the button group level.

> If the padding was set to `1em` already in the Figma Plugin, this spacing metadata wouldn't really do anything with the padding token, it would just stick to that `1em` as the current unit is already the desired unit.

## Challenges

There's no easy way to know what kinds of metadata should be inherited, and for some metadata, the inheritance could be problematic.

I think for now, it's only safe to do it for our own metadata under "studio.tokens" namespace, and "type" as this property is spec'd to be inherited in the W3C Design Token spec draft, I don't really see a risk with that one.

## Implementation

I'm thinking we could perhaps do this in StyleDictionary parse step, take the dictionary, recursively loop over everything and if we encounter a type of tokens-studio metadata, we can use something like `deepmerge` to merge it into the child token groups and tokens if "type" or tokens-studio meta already exists in children.

We should definitely test if this isn't too expensive of an action to be doing for all tokens..

@six7 would love your feedback on this.

### Would you be available to contribute this feature?

- [X] Yes, I would like to contribute this

**Comment by six7** [comment]
We already support setting type at the group level inside the plugin itself, so I'd love to see this in the transforms as well!

As for the metadata: definitely an interesting one! The base font size could be another one that you might want to set. We don't allow inheritance in the plugin, but users can basically define a 'root font size' which they could change eg from 16 to 20px or so (meaning 1rem has different sizes).

**Comment by jorenbroekema** [comment]
Now that we support W3C spec I don't really think this still necessary. I haven't seen or heard anyone mention needing this.
