### ISSUE TITLE
[Bug]: resolveMath removing "px" from the end of values

### ISSUE THREAD

**Issue by sofiamichel** [tokens-studio/sd-transforms#89]
### What happened?

Tokens that use typography or box shadow alias tokens were missing "px" from the end of each value. After some debugging I realized that it was fixed by removing the `resolveMath` transform.

### Reproduction

```
"alert" : {   
    "type": {
         "message": {
           "value": "{font.paragraph.md}",
           "type": "typography"
      },
}
```

Produces: `$alert-type-message: 500 16/1.25 CeraPro;` when `resolveMath` transform is used.
This happens for both typography tokens and boxShadow tokens

### Expected output

`$alert-type-message: 500 16px/1.25 CeraPro;`

### Version

0.5.6

**Comment by jorenbroekema** [comment]
Thanks for catching this one! I also ran into it when adding some more advanced use cases in my integration tests, I believe I fixed the issue, should be out in v0.6.0, though check the CHANGELOG.md as it contains a few breaking changes that may or may not impact you :)
